#!/usr/bin/env bash
# tools/policy.sh — read, render and verify THE policy declaration.
#
# Summary: policy/model.policy is the one place a tuned constant is written.
# This script is how shell reads it, how sql/01_policy.sql is generated from
# it, and how we prove the two have not drifted. SQL reads the same values
# through the generated view `v_model_policy`. ADR 0032.
#
#   tools/policy.sh get GAP_S             # 150
#   tools/policy.sh env                   # KEY=VALUE lines, safe to `eval`
#   tools/policy.sh version               # 1
#   tools/policy.sh hash                  # 12-hex content hash of the values
#   tools/policy.sh stamp                 # one-line evidence header
#   tools/policy.sh list                  # human-readable table
#   tools/policy.sh gen                   # regenerate sql/01_policy.sql
#   tools/policy.sh check [--database DB] # fail if anything has drifted
#
# `check` is a GATE. It runs in tools/test-all.sh and must stay cheap and
# dependency-free (no ClickHouse needed unless --database is given).
set -euo pipefail
cd "$(dirname "$0")/.."

POLICY_FILE=policy/model.policy
GEN_FILE=sql/01_policy.sql

die() { printf 'policy.sh: %s\n' "$*" >&2; exit 1; }
[ -f "$POLICY_FILE" ] || die "missing $POLICY_FILE — the declaration IS the source of truth"

# ---------------------------------------------------------------------------
# PARSER. One awk pass emits `tier<TAB>KEY<TAB>value<TAB>sqltype<TAB>note`.
# `#[section]` opens a tier; `#: <type> | <note>` annotates the NEXT key.
# Everything else that looks like KEY=VALUE is a key. Deliberately tolerant of
# a missing annotation (type defaults to String, note to empty) so adding a key
# is a one-line edit and the generator still produces valid SQL.
# ---------------------------------------------------------------------------
parse() {
  awk '
    /^#\[/            { tier = $0; sub(/^#\[/, "", tier); sub(/\].*$/, "", tier); next }
    /^#:/             { ann = substr($0, 3)
                        sub(/^[ \t]+/, "", ann)
                        ptype = ann; pnote = ""
                        if (index(ann, "|") > 0) {
                          ptype = substr(ann, 1, index(ann, "|") - 1)
                          pnote = substr(ann, index(ann, "|") + 1)
                        }
                        gsub(/^[ \t]+|[ \t]+$/, "", ptype)
                        gsub(/^[ \t]+|[ \t]+$/, "", pnote)
                        next }
    /^#/              { next }
    /^[ \t]*$/        { next }
    /^[A-Z][A-Z0-9_]*=/ {
                        key = $0; sub(/=.*$/, "", key)
                        val = $0; sub(/^[^=]*=/, "", val)
                        sub(/[ \t]+#.*$/, "", val)          # trailing comment
                        gsub(/^[ \t]+|[ \t]+$/, "", val)
                        t = (tier == "" ? "meta" : tier)
                        ty = (ptype == "" ? "String" : ptype)
                        printf "%s\t%s\t%s\t%s\t%s\n", t, key, val, ty, pnote
                        ptype = ""; pnote = ""
                        next }
    { printf "PARSE-ERROR\t%s\n", $0 }
  ' "$POLICY_FILE"
}

PARSED="$(parse)"
case "$PARSED" in *PARSE-ERROR*) die "unparseable line in $POLICY_FILE:
$(printf '%s\n' "$PARSED" | grep PARSE-ERROR)" ;; esac

field() {  # field <col> <KEY>
  printf '%s\n' "$PARSED" | awk -F'\t' -v k="$2" -v c="$1" '$2 == k { print $c; found = 1 }
                                                            END { if (!found) exit 3 }'
}

get() { field 3 "$1" || die "no such policy key: $1"; }

# Canonical form for hashing: KEY=VALUE, sorted, one per line. Includes
# POLICY_VERSION, so the hash is the identity of the whole declaration — a
# value edit that forgets the version bump still changes the hash, and
# `check` compares the hash baked into sql/01_policy.sql against this one.
canonical() { printf '%s\n' "$PARSED" | awk -F'\t' '{ printf "%s=%s\n", $2, $3 }' | LC_ALL=C sort; }

sha256() {
  if command -v shasum >/dev/null 2>&1; then shasum -a 256 | cut -c1-64
  elif command -v sha256sum >/dev/null 2>&1; then sha256sum | cut -c1-64
  else die "no shasum or sha256sum on PATH — cannot compute the policy hash"; fi
}
policy_hash() { canonical | sha256 | cut -c1-12; }

sqlq() { printf '%s' "$1" | sed "s/'/''/g"; }   # single-quote escape

# ---------------------------------------------------------------------------
# GENERATOR. Two views, and the long form is DERIVED FROM the wide one, so a
# value exists exactly once in the generated file too.
# ---------------------------------------------------------------------------
gen_sql() {
  local ver hash
  ver="$(get POLICY_VERSION)"
  hash="$(policy_hash)"
  cat <<EOF
-- ============================================================================
-- 01_policy.sql — THE POLICY, AS SQL SEES IT.
--
-- GENERATED by tools/policy.sh gen from policy/model.policy. DO NOT EDIT: the
-- declaration is policy/model.policy, this file is a rendering of it, and
-- \`tools/policy.sh check\` fails the build if the two disagree.
--
-- Why a view and not a table: a view is DDL, so applying it is non-destructive
-- and per-database — the graded database and a scratch database can hold
-- different policies without one silently rewriting the other (a server-wide
-- SQL UDF could not give that). A missing view is a LOUD error at query time,
-- where a missing row in a key/value table would resolve to a default and give
-- you GAP_S = 0 without a word.
--
-- Consumers read it as scalar subqueries:
--     WITH (SELECT gap_s FROM v_model_policy) AS GAP_S
-- which ClickHouse folds to a constant, so it is free inside a lambda.
--
-- policy version $ver, content hash $hash
-- ADR 0032 · inventory docs/DYNAMIC_PARAMS.md · sensitivity evidence/params/
-- ============================================================================

CREATE OR REPLACE VIEW v_model_policy AS
SELECT
EOF
  printf "    %-46s AS policy_hash,\n" "'$(sqlq "$hash")'"
  printf '%s\n' "$PARSED" | awk -F'\t' '
    { key = tolower($2); val = $3; ty = $4; note = $5
      if (ty == "String") expr = "\x27" val "\x27"; else expr = "to" ty "(" val ")"
      printf "    %-46s AS %s%s\n", expr, key, (NR_last ? "" : ",")
    }' | sed '$ s/,$//' | awk '{ print }'
  cat <<'EOF'
;

-- Long form, for humans and for evidence. Derived FROM the wide view above,
-- never from the declaration a second time.
CREATE OR REPLACE VIEW v_model_policy_kv AS
SELECT p.1 AS tier, p.2 AS key, p.3 AS value, p.4 AS note
FROM
(
    SELECT arrayJoin([
EOF
  printf "        ('meta', 'policy_hash', policy_hash, 'sha256(sorted KEY=VALUE), first 12 hex'),\n"
  printf '%s\n' "$PARSED" | awk -F'\t' '
    { key = tolower($2); note = $5; tier = $1
      gsub(/\x27/, "\x27\x27", note)
      printf "        (\x27%s\x27, \x27%s\x27, toString(%s), \x27%s\x27),\n", tier, key, key, note
    }' | sed '$ s/,$//'
  cat <<'EOF'
    ]) AS p
    FROM v_model_policy
);
EOF
}

# ---------------------------------------------------------------------------
# CONSISTENCY. Relations between declared values that must hold. These are the
# checks that make declaring PUBLISH_*_COVER_S worth more than the literals
# they replaced: raising TAIL_S past a cover now FAILS instead of silently
# under-covering the publisher's window (ADR 0028 §A2's latent cross-file break).
# ---------------------------------------------------------------------------
assert() {  # assert <condition-description> <lhs> <op> <rhs>
  local desc="$1" lhs="$2" op="$3" rhs="$4"
  if [ "$(awk -v a="$lhs" -v b="$rhs" -v o="$op" 'BEGIN{
        if (o == ">=") print (a >= b) ? 1 : 0;
        else if (o == ">") print (a > b) ? 1 : 0;
        else if (o == "in01") print (a == 0 || a == 1) ? 1 : 0;
        else print 0 }')" != 1 ]; then
    printf '   FAIL  %s  (%s %s %s)\n' "$desc" "$lhs" "$op" "$rhs"
    return 1
  fi
  printf '   ok    %s\n' "$desc"
}

consistency() {
  local rc=0 gap tail
  gap="$(get GAP_S)"; tail="$(get TAIL_S)"
  assert "GAP_S > 0"                                   "$gap"  ">"  0        || rc=1
  assert "TAIL_S >= 0"                                 "$tail" ">=" 0        || rc=1
  assert "UNCLOSED_PAUSE_TO_RUN_END is a flag"  "$(get UNCLOSED_PAUSE_TO_RUN_END)" in01 0 || rc=1
  assert "POINT_ACTIVITY_COUNTS is a flag"      "$(get POINT_ACTIVITY_COUNTS)"     in01 0 || rc=1
  # cover >= TAIL_S + 60: the +60 is the close delta landing in the minute
  # AFTER coverage ends. This is the relation ADR 0028 found broken-in-waiting.
  assert "PUBLISH_MINUTE_COVER_S >= TAIL_S + 60"       "$(get PUBLISH_MINUTE_COVER_S)"       ">=" "$((tail + 60))" || rc=1
  assert "PUBLISH_HOUR_COVER_S >= TAIL_S + 60"         "$(get PUBLISH_HOUR_COVER_S)"         ">=" "$((tail + 60))" || rc=1
  assert "PUBLISH_INTERVAL_PREFILTER_S >= TAIL_S + 60" "$(get PUBLISH_INTERVAL_PREFILTER_S)" ">=" "$((tail + 60))" || rc=1
  assert "PUBLISH_LOOKBACK_S > PUBLISH_SETTLE_S"       "$(get PUBLISH_LOOKBACK_S)"           ">"  "$(get PUBLISH_SETTLE_S)" || rc=1
  assert "PUBLISH_LEASE_TTL_S > PUBLISH_LEASE_SETTLE_S" "$(get PUBLISH_LEASE_TTL_S)"         ">"  "$(get PUBLISH_LEASE_SETTLE_S)" || rc=1
  assert "QUEUE_TTL_DAYS >= 1"                         "$(get QUEUE_TTL_DAYS)"               ">=" 1 || rc=1
  return $rc
}

# DDL that cannot read a view is DECLARED here and VERIFIED against the tree.
# ClickHouse TTL is part of the table definition and must be a deterministic
# expression over the table's own columns, so sql/12_publish.sql carries the
# literal. This check is what stops it drifting.
ttl_check() {
  local days rc=0 n secs
  days="$(get QUEUE_TTL_DAYS)"
  secs=$((days * 86400))
  n="$(grep -c "TTL toDateTime(.*) + INTERVAL ${days} DAY" sql/12_publish.sql || true)"
  if [ "$n" = 3 ]; then printf '   ok    sql/12_publish.sql: 3 queue TTLs at INTERVAL %s DAY\n' "$days"
  else printf '   FAIL  sql/12_publish.sql: expected 3 TTLs at INTERVAL %s DAY, found %s\n' "$days" "$n"; rc=1; fi
  # Everything that CAN read the view must read it. The lag view derives
  # retention_ttl_s from queue_ttl_days, so a bare 604800 anywhere in that file
  # is a copy that got left behind.
  # Comments stripped first — this file's own commentary QUOTES the literal it
  # replaced, and a scanner that greps prose as code blocks a clean tree.
  n="$(sed -e 's/--.*//' sql/12_publish.sql | grep -c "$secs" || true)"
  if [ "$n" = 0 ]; then printf '   ok    sql/12_publish.sql: no bare %s — retention derives from queue_ttl_days\n' "$secs"
  else printf '   FAIL  sql/12_publish.sql: %s literal %s still present; the view must read v_model_policy\n' "$n" "$secs"; rc=1; fi
  return $rc
}

# No literal may survive outside the declaration. This is the check that keeps
# ADR 0032 true a month from now: it greps the consumers for the pattern the
# constants used to be written in.
literal_check() {
  local rc=0 hits
  hits="$(grep -nE '^[[:space:]]*[0-9]+[[:space:]]+AS[[:space:]]+(GAP_S|TAIL_S|UNCLOSED_PAUSE_TO_RUN_END|POINT_ACTIVITY_COUNTS)\b' \
            sql/*.sql 2>/dev/null || true)"
  if [ -z "$hits" ]; then printf '   ok    no `<n> AS GAP_S`-style literals left in sql/\n'
  else printf '   FAIL  policy literals still in sql/:\n%s\n' "$hits"; rc=1; fi
  hits="$(grep -nE '^(GAP_S|TAIL_S)[[:space:]]*(,[[:space:]]*TAIL_S)?[[:space:]]*=[[:space:]]*[0-9]' \
            tools/reference_interpreter.py tools/cruel-gen.sh tools/golden-gen.sh 2>/dev/null || true)"
  if [ -z "$hits" ]; then printf '   ok    no GAP_S/TAIL_S literals left in the oracle or the generators\n'
  else printf '   FAIL  policy literals still in tools/:\n%s\n' "$hits"; rc=1; fi
  return $rc
}

db_check() {  # db_check <database>
  local db="$1" rc=0 got want key
  # Read the deployed view. `tools/ch` is used so target resolution stays in
  # one place; CH_DATABASE is stripped so an exported graded database name
  # cannot redirect a local check.
  local out
  out="$(env -u CH_DATABASE CH_DATABASE_LOCAL="$db" tools/ch \
        "SELECT key, value FROM v_model_policy_kv WHERE tier != 'meta' FORMAT TSV" 2>&1)" \
    || { printf '   FAIL  %s: cannot read v_model_policy_kv — has sql/01_policy.sql been applied?\n%s\n' "$db" "$out"; return 1; }
  while IFS="$(printf '\t')" read -r key got; do
    [ -n "$key" ] || continue
    want="$(field 3 "$(printf '%s' "$key" | tr '[:lower:]' '[:upper:]')" || true)"
    if [ "$got" != "$want" ]; then
      printf '   FAIL  %s: deployed %s=%s, declared %s\n' "$db" "$key" "$got" "$want"; rc=1
    fi
  done <<EOF
$out
EOF
  got="$(env -u CH_DATABASE CH_DATABASE_LOCAL="$db" tools/ch "SELECT policy_hash FROM v_model_policy FORMAT TSVRaw" | tr -d '[:space:]')"
  want="$(policy_hash)"
  if [ "$got" = "$want" ]; then printf '   ok    %s: deployed policy hash %s matches the declaration\n' "$db" "$got"
  else printf '   FAIL  %s: deployed policy hash %s != declared %s — re-apply sql/01_policy.sql\n' "$db" "$got" "$want"; rc=1; fi
  return $rc
}

# ---------------------------------------------------------------------------
CMD="${1:-}"; shift || true
case "$CMD" in
  get)      get "${1:?usage: policy.sh get KEY}" ;;
  env)      printf '%s\n' "$PARSED" | awk -F'\t' '{ printf "%s=%s\n", $2, $3 }' ;;
  version)  get POLICY_VERSION ;;
  hash)     policy_hash ;;
  stamp)
    printf 'policy v%s (%s) GAP_S=%s TAIL_S=%s UNCLOSED_PAUSE_TO_RUN_END=%s POINT_ACTIVITY_COUNTS=%s\n' \
      "$(get POLICY_VERSION)" "$(policy_hash)" "$(get GAP_S)" "$(get TAIL_S)" \
      "$(get UNCLOSED_PAUSE_TO_RUN_END)" "$(get POINT_ACTIVITY_COUNTS)" ;;
  list)
    printf 'policy v%s   content hash %s\n\n' "$(get POLICY_VERSION)" "$(policy_hash)"
    printf '%-10s %-30s %-8s %s\n' TIER KEY VALUE NOTE
    printf '%s\n' "$PARSED" | awk -F'\t' '{ printf "%-10s %-30s %-8s %s\n", $1, $2, $3, $5 }' ;;
  gen)
    gen_sql > "$GEN_FILE.tmp" && mv "$GEN_FILE.tmp" "$GEN_FILE"
    printf 'wrote %s  (policy v%s, hash %s)\n' "$GEN_FILE" "$(get POLICY_VERSION)" "$(policy_hash)" ;;
  check)
    DB=""
    while [ $# -gt 0 ]; do
      case "$1" in
        --database)   DB="${2:?--database needs a name}"; shift 2 ;;
        --database=*) DB="${1#--database=}"; shift ;;
        *) die "unknown argument to check: $1" ;;
      esac
    done
    RC=0
    echo "== policy check   v$(get POLICY_VERSION)  hash $(policy_hash)"
    echo "-- generated SQL is current"
    if gen_sql | diff -u "$GEN_FILE" - >/dev/null 2>&1; then
      printf '   ok    %s matches policy/model.policy\n' "$GEN_FILE"
    else
      printf '   FAIL  %s is STALE. Run: tools/policy.sh gen\n' "$GEN_FILE"
      gen_sql | diff -u "$GEN_FILE" - | head -40 || true
      RC=1
    fi
    echo "-- declared values are internally consistent"
    consistency || RC=1
    echo "-- DDL that cannot read the view still agrees with it"
    ttl_check || RC=1
    echo "-- no consumer carries its own literal"
    literal_check || RC=1
    if [ -n "$DB" ]; then
      echo "-- deployed policy in database '$DB'"
      db_check "$DB" || RC=1
    fi
    if [ "$RC" = 0 ]; then echo "== policy check PASS"; else echo "== policy check FAIL" >&2; fi
    exit "$RC" ;;
  ""|-h|--help) sed -n '2,20p' "$0" >&2; exit 2 ;;
  *) die "unknown command: $CMD" ;;
esac
