packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@swc/core': true
  cbor-extract: true
  esbuild: true
  node: true
  protobufjs: false
  sharp: false

minimumReleaseAgeExclude:
  - "@types/pg"
  - "@ai-sdk/*"
  - "@rolldown/*"
  - "@vercel/*"
  - "@workflow/*"
  - ai
  - experimental-ai-sdk-code-mode
  - eve
  - nitro
  - rolldown
  - workflow
