CREATE TABLE gold.metrics_hourly
(
    `hour` DateTime('UTC') COMMENT 'Hour bucket in UTC, truncated to :00:00. ORDER BY position 3. Filter with WHERE hour >= ... AND hour < ... for granule pruning after region+ad_format.',
    `ad_format` LowCardinality(String) COMMENT 'Ad creative format. Enum: banner, native, interstitial, video, rewarded. ORDER BY position 2 (leading filter after region).',
    `app_category` LowCardinality(String) COMMENT 'App category. Enum values: gaming, ecommerce, entertainment, news, finance, social, utility. To translate back to specific app_ids in this cell, inspect the app_ids array column or JOIN with gold.dict_apps.',
    `publisher_tier` LowCardinality(String) COMMENT 'Publisher revenue tier. Enum values: tier_1 (highest revenue), tier_2, tier_3. Tier_1 publishers typically have higher fill rate and eCPM.',
    `region` LowCardinality(String) COMMENT 'Global region. Enum values: EU, NAM, APAC, LATAM, MEA. ORDER BY position 1 = leading filter for granule pruning. Include WHERE region = ... first in RCA-style filters when possible.',
    `country` LowCardinality(String) COMMENT 'ISO 3166-1 alpha-2 country code (2 letters), e.g. DE, US, IN, BR.',
    `device_model` LowCardinality(String) COMMENT 'Device brand + model string, e.g. "Pixel 7", "iPhone 15", "Galaxy S24".',
    `os_version` LowCardinality(String) COMMENT 'OS + major version string, e.g. "Android 14", "iOS 17", "HarmonyOS 4".',
    `vertical` LowCardinality(String) COMMENT 'Advertiser industry vertical. Enum values: gaming, entertainment, finance, ecommerce, auto, travel, cpg. Empty string "" for cells composed of unfilled events (no matching advertiser). Filter with WHERE vertical != "" to include only filled inventory. Filter with WHERE vertical = "" to isolate unfilled requests.',
    `campaign_type` LowCardinality(String) COMMENT 'Campaign pricing/optimisation model. Enum values: CPM (cost per mille impressions), CPC (cost per click), CPI (cost per install). Empty string "" for unfilled cells (same convention as vertical).',
    `requests` UInt64 COMMENT 'Count of ad requests (each source event = one request). Additive. Denominator of fill_rate (sum(fills)/sum(requests)) and rpr (sum(revenue)/sum(requests)). READ WITH sum(requests).',
    `fills` UInt64 COMMENT 'Count of filled ad requests (source is_filled=1). Additive. Numerator of fill_rate, denominator of render_rate (sum(impressions)/sum(fills)). READ WITH sum(fills).',
    `impressions` UInt64 COMMENT 'Count of rendered impressions (source is_impression=1). Additive. Denominator of ctr (sum(clicks)/sum(impressions)) and ecpm (sum(revenue)/sum(impressions)*1000). READ WITH sum(impressions).',
    `clicks` UInt64 COMMENT 'Count of clicks (source is_click=1). Additive. Numerator of ctr. READ WITH sum(clicks).',
    `revenue` Float64 COMMENT 'Revenue in USD (US dollars). Sub-cent granularity per source event; sums to dollars per row. Additive. Numerator of ecpm and rpr. READ WITH sum(revenue).',
    `app_ids` SimpleAggregateFunction(groupUniqArrayArray, Array(String)) COMMENT 'Union-dedup set of app_ids whose silver events aggregated into this row. Single-row: SELECT app_ids (Array(String)). Cross-row: groupUniqArrayArray(app_ids). Membership: has(app_ids, \'app_00123\'). Count: length(app_ids).',
    `geo_device_ids` SimpleAggregateFunction(groupUniqArrayArray, Array(String)) COMMENT 'Union-dedup set of geo_device_ids whose events aggregated into this row. Same query patterns as app_ids: SELECT / groupUniqArrayArray / has / length.',
    `advertiser_ids` SimpleAggregateFunction(groupUniqArrayArray, Array(String)) COMMENT 'Union-dedup set of advertiser_ids whose events aggregated into this row. Empty array [] for cells composed of unfilled events (advertiser_id="" is filtered out in the MV, not stored). Same query patterns as app_ids.'
)
ENGINE = SharedSummingMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}', (requests, fills, impressions, clicks, revenue))
PARTITION BY toYYYYMM(hour)
PRIMARY KEY (region, ad_format, hour)
ORDER BY (region, ad_format, hour, app_category, publisher_tier, vertical, campaign_type, country, device_model, os_version)
SETTINGS index_granularity = 8192
COMMENT 'THE ONE FACT TABLE. Hourly InMobi ad-metrics rollup at ATTRIBUTE grain (hour × ad_format × app_category × publisher_tier × region × country × device_model × os_version × vertical × campaign_type). Every ad event with matching attribute values is collapsed into one row here. Contains 5 additive measures (requests, fills, impressions, clicks, revenue) and 3 unique-set arrays (app_ids, geo_device_ids, advertiser_ids) preserving the raw IDs behind each cell. READ CONTRACT: always wrap measures in sum() and GROUP BY any subset of the 10 attribute columns (never SELECT a bare measure without sum()). DERIVED METRICS: fill_rate = sum(fills)/sum(requests), render_rate = sum(impressions)/sum(fills), ctr = sum(clicks)/sum(impressions), ecpm = sum(revenue)/sum(impressions)*1000, rpr = sum(revenue)/sum(requests). ID SET USAGE: cross-row aggregate via groupUniqArrayArray(app_ids|geo_device_ids|advertiser_ids); membership filter via has(<col>, \'<id>\'); cardinality via length(<col>) on single row or length(groupUniqArrayArray(<col>)) across rows. NOTES: (1) unfilled events land with vertical=""/campaign_type="" and empty advertiser_ids; filter WHERE vertical != "" to exclude, WHERE vertical = "" to isolate; (2) hour bucket is UTC; (3) primary key = (region, ad_format, hour), put these first in WHERE for granule pruning; (4) revenue is in USD dollars.'
