"""Langfuse wrapper with a NullTracer fallback (ENGINEERING.md §4.2, §6.2).

Deterministic-first (D6): the pipeline must run with no keys at all. When
Langfuse credentials are absent we emit the same span structure to stdout so
the traceability contract (one trace per run, spans per agent/query/tool)
holds regardless — `atlys.event_log` is the independent audit trail either way.

Gotcha from the plan: Langfuse has no MCP middleware — each MCP tool handler is
wrapped in a span manually (we do that in mcp_server.py).
"""
from __future__ import annotations

import logging
import uuid
from contextlib import contextmanager
from typing import Iterator, Protocol

log = logging.getLogger("atlys.tracing")


class Tracer(Protocol):
    def start(self, name: str, session_id: str | None = None) -> str: ...
    @contextmanager
    def span(self, name: str, **meta) -> Iterator[None]: ...
    def flush(self) -> None: ...


class _NoopSpan:
    def __enter__(self):
        return self

    def __exit__(self, *exc):
        return False


class NullTracer:
    """No external tracing — logs spans to stdout in a tree-ish format.

    Keeps the exact same call surface as LangfuseTracer so agents don't care
    which one is live.
    """

    def __init__(self, trace_id: str | None = None):
        self.trace_id = trace_id or f"trace-{uuid.uuid4().hex[:12]}"
        self._depth = 0

    def start(self, name: str, session_id: str | None = None) -> str:
        # one fresh trace per run — mirrors LangfuseTracer semantics
        self.trace_id = f"trace-{uuid.uuid4().hex[:12]}"
        log.info("TRACE %s (%s) session=%s", self.trace_id, name, session_id or "")
        return self.trace_id

    @contextmanager
    def span(self, name: str, **meta) -> Iterator[_NoopSpan]:
        indent = "  " * self._depth
        meta_s = " " + " ".join(f"{k}={v}" for k, v in meta.items()) if meta else ""
        log.info("%s├─ span %s%s", indent, name, meta_s)
        self._depth += 1
        try:
            yield _NoopSpan()
        finally:
            self._depth -= 1
            output = meta.get("output")
            if output:
                log.info("%s└─ output %s", indent, output)

    def flush(self) -> None:
        pass


class LangfuseTracer:
    """Real Langfuse trace — one trace per spec run, spans per step.

    The trace id is generated by Langfuse and propagated everywhere (every
    `meta.*` row + `atlys.event_log` row carries it, §5.4). We also set
    `session_id = run_id` for the dual-trace cross-link (§6.2).

    Uses the langfuse SDK v2 API (`client.trace(...)` / `trace.span(...)`):
    v4 removed those in favour of the observe() decorator API, so we pin
    `langfuse>=2.30,<3` in requirements.txt.
    """

    def __init__(self, public_key: str, secret_key: str, base_url: str):
        from langfuse import Langfuse  # deferred so NullTracer needs no dep

        self._client = Langfuse(public_key=public_key, secret_key=secret_key, host=base_url)
        self._trace = None
        self.trace_id: str | None = None

    def start(self, name: str, session_id: str | None = None) -> str:
        self._trace = self._client.trace(name=name, session_id=session_id)
        self.trace_id = self._trace.id
        return self.trace_id

    @contextmanager
    def span(self, name: str, **meta) -> Iterator[_NoopSpan]:
        if self._trace is None:  # defensive: start() was never called
            yield _NoopSpan()
            return
        # StatefulSpanClient is NOT a context manager in the v2 SDK — create
        # it, yield, then end() it on exit (input/output passed as kwargs).
        span = self._trace.span(name=name, input=meta.get("input"))
        try:
            yield _NoopSpan()
        finally:
            try:
                # output may be populated by the caller during the span
                # (e.g. playbook row_count/elapsed) — set it before end().
                out = meta.get("output")
                if out is not None:
                    span.update(output=out)
                span.end()
            except Exception:  # noqa: BLE001 - never let observability break the pipeline
                log.exception("langfuse span end failed")


def make_tracer(
    public_key: str | None,
    secret_key: str | None,
    base_url: str | None = None,
    trace_id: str | None = None,
) -> Tracer:
    """Factory: LangfuseTracer when keys exist, NullTracer otherwise."""
    if public_key and secret_key:
        return LangfuseTracer(public_key, secret_key, base_url or "https://cloud.langfuse.com")
    return NullTracer(trace_id=trace_id)
