"""Persistence for investigation history, the scanner's event feed, and
follow-up chat -- all in ClickHouse (`clickhouse/app_state.sql`), no new
datastore introduced. Every write here is best-effort and never raises to
the caller: a persistence failure must not fail or block the actual
investigation response, only get logged -- the deterministic evidence is
correct and already returned regardless of whether history-keeping succeeds.
"""

import json
import logging
import uuid
from datetime import datetime
from typing import Optional

from engine.ch_client import get_client
from engine.pipeline import InvestigationResult

logger = logging.getLogger(__name__)

_INVESTIGATION_COLUMNS = [
    "id", "triggered_by", "metric", "window_start", "window_end",
    "current_value", "baseline_mean", "baseline_sample_count", "zscore",
    "is_anomalous", "insufficient_baseline", "primary_factor",
    "narration", "narration_available", "narration_provider", "narration_error",
    "langfuse_trace_url", "evidence_json",
]


def save_investigation(result: InvestigationResult, triggered_by: str = "manual") -> Optional[str]:
    """Persists one investigation to the `investigations` table. Returns the
    new investigation id, or None if persistence failed -- callers must treat
    a None return as "not saved to history" and continue normally, never as
    an investigation failure."""
    ev = result.evidence
    n = result.narration
    inv_id = str(uuid.uuid4())
    try:
        evidence_json = json.dumps(ev.model_dump(mode="json"))
        row = [
            inv_id, triggered_by, ev.metric, ev.window_start, ev.window_end,
            ev.current_value, ev.baseline_mean, ev.baseline_sample_count, ev.zscore,
            1 if ev.is_anomalous else 0, 1 if ev.insufficient_baseline else 0, ev.primary_factor or "",
            n.narration or "", 1 if n.available else 0, n.provider, n.error or "",
            result.langfuse_trace_url or "", evidence_json,
        ]
        get_client().insert("investigations", [row], _INVESTIGATION_COLUMNS, step="store:save_investigation")
        return inv_id
    except Exception as e:
        logger.warning("Failed to persist investigation: %s", e)
        return None


def list_investigations(limit: int = 50) -> list:
    """Most recent investigations first, bounded -- never an unbounded scan."""
    limit = min(limit, 200)
    try:
        rows = get_client().query(
            "SELECT id, created_at, triggered_by, metric, window_start, window_end, current_value, "
            "baseline_mean, zscore, is_anomalous, insufficient_baseline, primary_factor, "
            "narration_available, langfuse_trace_url "
            f"FROM investigations ORDER BY created_at DESC LIMIT {limit}",
            step="store:list_investigations",
            trace=_ScratchTrace(),
        )
        for r in rows:
            r["id"] = str(r["id"])  # clickhouse_connect maps UUID columns to uuid.UUID -- normalize to str for API consumers
        return rows
    except Exception as e:
        logger.warning("Failed to list investigations: %s", e)
        return []


def get_investigation(investigation_id: str) -> Optional[dict]:
    try:
        # investigation_id is always a str(uuid.uuid4()) generated by this module,
        # never raw user input, but escape defensively anyway.
        safe_id = investigation_id.replace("'", "")
        rows = get_client().query(
            f"SELECT * FROM investigations WHERE id = '{safe_id}' LIMIT 1",
            step="store:get_investigation",
            trace=_ScratchTrace(),
        )
        if not rows:
            return None
        row = rows[0]
        row["id"] = str(row["id"])
        row["evidence"] = json.loads(row["evidence_json"])
        return row
    except Exception as e:
        logger.warning("Failed to fetch investigation %s: %s", investigation_id, e)
        return None


def save_scan_tick(
    metric: str,
    window_start: datetime,
    window_end: datetime,
    current_value: float,
    baseline_mean: float,
    zscore: float,
    is_anomalous: bool,
    investigation_id: Optional[str] = None,
) -> None:
    try:
        row = [
            str(uuid.uuid4()), metric, window_start, window_end,
            current_value, baseline_mean, zscore, 1 if is_anomalous else 0, investigation_id,
        ]
        get_client().insert(
            "scan_ticks", [row],
            ["id", "metric", "window_start", "window_end", "current_value", "baseline_mean", "zscore", "is_anomalous", "investigation_id"],
            step="store:save_scan_tick",
        )
    except Exception as e:
        logger.warning("Failed to persist scan tick: %s", e)


def list_scan_ticks(limit: int = 100) -> list:
    limit = min(limit, 500)
    try:
        rows = get_client().query(
            f"SELECT * FROM scan_ticks ORDER BY ts DESC LIMIT {limit}",
            step="store:list_scan_ticks",
            trace=_ScratchTrace(),
        )
        for r in rows:
            r["id"] = str(r["id"])
            r["investigation_id"] = str(r["investigation_id"]) if r.get("investigation_id") else None
        return rows
    except Exception as e:
        logger.warning("Failed to list scan ticks: %s", e)
        return []


# Chat turns hang off a SUBJECT, which is either an investigation or an incident.
#
# Both ids are UUIDs from `investigations.investigation_id` and `incidents.incident_id`
# respectively, so one table keyed by UUID holds both without ambiguity -- two randomly
# generated UUIDs do not collide, and a transcript is only ever read back by the id that
# wrote it. The column keeps its original name because renaming it would be a DDL
# migration against a live table for no behavioural gain; the parameter name says what it
# actually is now.
#
# Why an incident needs its own transcript at all: only the top few incidents per sweep
# are fully investigated (settings.max_investigations_per_sweep), so most incidents have
# no investigation_id -- and before this, that meant no chat on most incident pages.

def save_chat_turn(subject_id: str, turn_index: int, role: str, content: str) -> None:
    try:
        get_client().insert(
            "investigation_chat",
            [[subject_id, turn_index, role, content]],
            ["investigation_id", "turn_index", "role", "content"],
            step="store:save_chat_turn",
        )
    except Exception as e:
        logger.warning("Failed to persist chat turn: %s", e)


def list_chat_turns(subject_id: str) -> list:
    try:
        return get_client().query(
            f"SELECT turn_index, role, content, created_at FROM investigation_chat "
            f"WHERE investigation_id = '{subject_id}' ORDER BY turn_index ASC",
            step="store:list_chat_turns",
            trace=_ScratchTrace(),
        )
    except Exception as e:
        logger.warning("Failed to list chat turns for %s: %s", subject_id, e)
        return []


class _ScratchTrace:
    """A throwaway Trace-like sink for store.py's own queries -- these are
    persistence plumbing, not part of any investigation's own evidence trace,
    so they're logged for ch_client's retry/error handling but discarded
    rather than attached to a real Trace object."""

    def record(self, entry) -> None:
        pass
