"""The Context Agent: a living, versioned context layer that argues with the data.

The pitch in one paragraph. Most "context layers" are a markdown file pasted into a
prompt; they rot silently and nobody can tell you which version produced which number.
Here the context lives in ClickHouse as an append-only, versioned log. Every LLM call in
this codebase is forced to declare the `context_version` it consumed. And because the
context sits in the same engine as `system.columns` and the event data, every claim the
documentation makes is *checkable*: the agent runs a query against each claim and stores
the query, its result, and a verified flag alongside the contradiction. The LLM proposes;
SQL adjudicates.

Public API (what the pipeline calls):

    bootstrap(base_context_md, ch) -> int                  # returns the context version
    snapshot(ch) -> ContextSnapshot
    reconcile(ch, new_tables, proposal) -> ContextDiff
    render_markdown(ch, out_dir) -> dict[str, Path]

`reconcile` is the interesting one. After a feature table lands it diffs the schema
fingerprint, auto-documents whatever appeared, re-runs every contradiction check against
the *new* reality, writes the changelog and bumps the snapshot. Check C6 in particular is
generated by our own pipeline: base_context.md asserts that every table joins on
`user_id`; the agent measures that on the freshly-landed table, finds it false, and writes
a data-quality entry that downstream findings cite as a caveat.
"""

from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Sequence

import tracing
from contracts import ContextDiff, ContextEntry, ContextSnapshot, Contradiction, DDLProposal

from contextlayer.bootstrap import parse_base_context, table_doc_entries
from contextlayer.checks import CheckOutput, Reality, run_all_checks
from contextlayer.store import OPS_TABLES, ContextStore, system_select

SOLUTION_DIR = Path(__file__).resolve().parents[1]
ATLYS_DIR = SOLUTION_DIR.parent
DEFAULT_BASE_CONTEXT = ATLYS_DIR / "base_context.md"
DEFAULT_OUT_DIR = SOLUTION_DIR / "out" / "context"


class ContextAgent:
    """Owns the context layer. Stateless between calls -- ClickHouse holds the state."""

    def __init__(self, ch: Any, run_id: str = "") -> None:
        self.ch = ch
        self.run_id = run_id
        self.store = ContextStore(ch, run_id=run_id)

    # ---------------------------------------------------------------- setup

    def ensure_schema(self) -> None:
        self.store.ensure_schema()

    # ------------------------------------------------------------ bootstrap

    def bootstrap(self, base_context_md: str | Path = DEFAULT_BASE_CONTEXT) -> int:
        """Parse base_context.md into the context layer. Idempotent.

        Re-running on an unchanged document writes zero rows and returns the same
        version -- which is precisely what makes the version number worth printing.
        """
        with tracing.span("context.bootstrap", source=str(base_context_md)) as sp:
            self.ensure_schema()
            path = Path(base_context_md)
            md = path.read_text(encoding="utf-8")

            reality = Reality(self.ch)
            entries = parse_base_context(
                md,
                known_tables=reality.tables,
                known_columns=reality.all_columns,
                source_ref=path.name,
            )
            diff = self.store.upsert(
                entries,
                change_reason=f"bootstrap from {path.name}",
                changed_by="context_agent.bootstrap",
            )
            fingerprint = self.store.capture_schema_fingerprint()
            snap = self.store.snapshot(
                note=f"bootstrap from {path.name}", schema_fingerprint=fingerprint
            )
            sp.update(
                metadata={
                    "entries_parsed": len(entries),
                    "added": len(diff.added),
                    "updated": len(diff.updated),
                    "context_version": snap.version,
                    "schema_fingerprint": fingerprint[:16],
                }
            )
            return snap.version

    # ------------------------------------------------------------- snapshot

    def snapshot(self, note: str = "") -> ContextSnapshot:
        with tracing.span("context.snapshot") as sp:
            snap = self.store.snapshot(note=note)
            sp.update(metadata={"context_version": snap.version, "entries": len(snap.entries)})
            return snap

    def current_version(self) -> int:
        return self.store.context_version()

    # ------------------------------------------------------------ reconcile

    def reconcile(
        self,
        new_tables: Sequence[str] = (),
        proposal: DDLProposal | None = None,
        note: str = "",
        use_llm: bool = False,
    ) -> ContextDiff:
        """Fold newly-landed reality into the context layer and re-adjudicate every claim.

        Stages (each its own trace span):
          1. schema fingerprint diff  -- what appeared since the last capture
          2. auto-documentation       -- table_doc/column_doc for new tables and columns
          3. checks                   -- C1..C6, each verified by an executed query
          4. write-back               -- entries proposed by checks, disputes, changelog
          5. snapshot                 -- new version, deterministic id
        """
        before = self.store.context_version()
        before_snapshot = self.store.snapshot_id_for_version(before)

        # ---- 1. schema delta ------------------------------------------------
        with tracing.span("context.reconcile.schema_diff") as sp:
            delta = self.store.schema_delta(before_run_id=self.run_id)
            declared = [t for t in new_tables if t not in OPS_TABLES]
            detected = [t for t in delta["new_tables"] if t not in OPS_TABLES]
            tables = sorted(set(declared) | set(detected))
            fingerprint = self.store.capture_schema_fingerprint()
            sp.update(
                metadata={
                    "new_tables_declared": declared,
                    "new_tables_detected": detected,
                    "new_columns": delta["new_columns"][:50],
                    "retyped_columns": delta["retyped_columns"][:50],
                    "fingerprint": fingerprint[:16],
                    "previous_fingerprint": delta["previous_fingerprint"][:16],
                }
            )

        reality = Reality(self.ch)

        # ---- 2. auto-documentation -----------------------------------------
        with tracing.span("context.reconcile.auto_document") as sp:
            auto: list[dict[str, Any]] = []
            for table in tables:
                if table not in reality.columns_by_table:
                    continue
                cols = list(reality.columns_by_table[table].items())
                auto.extend(
                    table_doc_entries(
                        table,
                        cols,
                        note=_proposal_note(proposal, table),
                        row_count=reality.row_counts.get(table),
                    )
                )
            # Columns that appeared on tables we already knew about.
            for ref in delta["new_columns"]:
                table, _, column = ref.partition(".")
                ctype = reality.columns_by_table.get(table, {}).get(column)
                if not ctype:
                    continue
                auto.append(
                    {
                        "entry_id": f"column.{table}.{column}",
                        "kind": "column_doc",
                        "key": ref,
                        "body": f"{column} {ctype} on {table} (added since the previous schema capture).",
                        "formula": "",
                        "refs": [table, column],
                        "source": "context_agent",
                        "source_ref": "system.columns",
                        "status": "active",
                        "confidence": 1.0,
                    }
                )
            if proposal is not None:
                auto.extend(_proposal_entries(proposal))
            auto_diff = self.store.upsert(
                auto,
                change_reason=f"auto-documented from the live schema ({', '.join(tables) or 'no new tables'})",
                changed_by="context_agent.reconcile",
            )
            sp.update(
                metadata={"auto_entries": len(auto), "added": len(auto_diff.added),
                          "updated": len(auto_diff.updated)}
            )

        # ---- 3. checks ------------------------------------------------------
        with tracing.span("context.reconcile.checks") as sp:
            entries = self.store.current()
            formulas = {eid: r.get("formula", "") for eid, r in self.store.raw_by_id().items()}
            result: CheckOutput = run_all_checks(
                self.ch,
                entries,
                formulas=formulas,
                new_tables=tables,
                run_id=self.run_id,
                reality=Reality(self.ch),  # refreshed: auto-doc may have added ops rows
                use_llm=use_llm,
                context_version=before,
            )
            contradictions = self.store.record_contradictions(result.contradictions)
            sp.update(
                metadata={
                    "contradictions": len(contradictions),
                    "verified": sum(1 for c in contradictions if c.verified),
                    "by_kind": _count_by(contradictions, "kind"),
                    "by_severity": _count_by(contradictions, "severity"),
                    "by_detector": _count_by(contradictions, "detected_by"),
                }
            )

        # ---- 4. write-back --------------------------------------------------
        with tracing.span("context.reconcile.write_back") as sp:
            check_diff = self.store.upsert(
                result.proposed_entries,
                change_reason="written by a contradiction check (measured, not assumed)",
                changed_by="context_agent.checks",
            )
            dispute_diff = self.store.dispute(
                result.disputed_entry_ids,
                reason="named by an unresolved uncomputable_metric contradiction",
            )
            sp.update(
                metadata={
                    "entries_from_checks": len(result.proposed_entries),
                    "disputed": result.disputed_entry_ids,
                }
            )

        # ---- 5. snapshot ----------------------------------------------------
        with tracing.span("context.reconcile.snapshot") as sp:
            snap = self.store.snapshot(
                note=note or f"reconcile after {', '.join(tables) or 'no new tables'}",
                schema_fingerprint=fingerprint,
            )
            sp.update(metadata={"context_version": snap.version, "entries": len(snap.entries)})

        if before_snapshot:
            diff = self.store.diff(before_snapshot, self.store.snapshot_id_for_version(snap.version))
        else:
            diff = ContextDiff(
                from_version=before,
                to_version=snap.version,
                added=auto_diff.added + check_diff.added,
                updated=auto_diff.updated + check_diff.updated + dispute_diff.updated,
            )
        diff.from_version = before
        diff.to_version = snap.version
        diff.contradictions = contradictions
        diff.gaps = sorted(
            {
                f"{c.kind}: {c.title}"
                for c in contradictions
                if c.kind in ("undefined_term", "uncomputable_metric", "join_assumption_violated")
            }
        )
        return diff

    # --------------------------------------------------------------- render

    def render_markdown(self, out_dir: str | Path = DEFAULT_OUT_DIR) -> dict[str, Path]:
        """Render the context layer to markdown.

        The ClickHouse tables are the source of truth; this is only a human view, and it
        says so in its own header. Regenerating it is always safe.
        """
        with tracing.span("context.render_markdown") as sp:
            out = Path(out_dir)
            out.mkdir(parents=True, exist_ok=True)
            version = self.store.context_version()
            snapshot_id = self.store.snapshot_id_for_version(version)
            snap_rows = self.store.snapshot_rows(limit=1)
            fingerprint = snap_rows[0]["schema_fingerprint"] if snap_rows else ""
            entries = self.store.current()
            contradictions = self.store.contradictions(limit=200)
            disputed = self.store.disputed_entry_ids()

            ctx_path = out / f"context_v{version}.md"
            ctx_path.write_text(
                _render_context(version, snapshot_id, fingerprint, entries, contradictions, disputed),
                encoding="utf-8",
            )
            log_path = out / "CHANGELOG.md"
            log_path.write_text(
                _render_changelog(self.store.changelog(limit=1000), self.store.snapshot_rows(limit=50)),
                encoding="utf-8",
            )
            sp.update(
                metadata={
                    "context_version": version,
                    "entries": len(entries),
                    "files": [str(ctx_path), str(log_path)],
                }
            )
            return {"context": ctx_path, "changelog": log_path}


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------


def _count_by(items: Sequence[Any], attr: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for i in items:
        k = str(getattr(i, attr))
        out[k] = out.get(k, 0) + 1
    return out


def _proposal_note(proposal: DDLProposal | None, table: str) -> str:
    if proposal is None or proposal.table_name != table:
        return ""
    bits = [f"ORDER BY ({', '.join(proposal.order_by)})"]
    if proposal.partition_by:
        bits.append(f"PARTITION BY {proposal.partition_by}")
    if proposal.ttl:
        bits.append(f"TTL {proposal.ttl}")
    reason = proposal.rationale.get("order_by", "")
    if reason:
        bits.append(f"order_by rationale: {reason}")
    return "; ".join(bits)


def _proposal_entries(proposal: DDLProposal) -> list[dict[str, Any]]:
    """Turn the instrumentation agent's derived semantics into context entries.

    This is what lets the Analytics Agent read *why* a table is shaped the way it is
    from the context layer rather than from another agent's return value.
    """
    s = proposal.semantics
    slug = s.feature_slug
    entries: list[dict[str, Any]] = [
        {
            "entry_id": f"entity.{slug}.entity_key",
            "kind": "entity",
            "key": f"{slug} entity key: {s.entity_key}",
            "body": (
                f"The grain of `{s.table_fqn}` is `{s.entity_key}` "
                f"(confidence {s.entity_key_confidence:.2f}); secondary keys: "
                f"{', '.join(s.secondary_keys) or 'none'}. Derived from the spec and the raw "
                f"events by the instrumentation agent, not assumed."
            ),
            "formula": "",
            "refs": sorted({proposal.table_name, s.entity_key, *s.secondary_keys}),
            "source": "instrumentation_agent",
            "source_ref": f"DDLProposal:{proposal.table_name}",
            "status": "active",
            "confidence": float(s.entity_key_confidence),
        },
        {
            "entry_id": f"business_def.{slug}.funnel",
            "kind": "business_def",
            "key": f"{slug} funnel",
            "body": (
                f"Ordered steps on `{s.table_fqn}`: {' -> '.join(s.ordered_steps) or 'none derived'} "
                f"(step order source: {s.step_order_source}). Segment dimensions: "
                f"{', '.join(s.segment_dims) or 'none'}. Event discriminator column: "
                f"`{s.event_column}`."
            ),
            "formula": "",
            "refs": sorted({proposal.table_name, s.event_column, *s.segment_dims}),
            "source": "instrumentation_agent",
            "source_ref": f"DDLProposal:{proposal.table_name}",
            "status": "active",
            "confidence": 1.0,
        },
    ]
    if s.partial_identity_columns:
        entries.append(
            {
                "entry_id": f"gap.data_quality.{proposal.table_name}.partial_identity",
                "kind": "gap",
                "key": f"{proposal.table_name}: partial identity coverage",
                "body": (
                    f"Columns with < 100% coverage on `{proposal.table_name}`: "
                    f"{', '.join(s.partial_identity_columns)}. House rules forbid Nullable on hot "
                    f"columns, so these default to the empty string. Every distinct count over "
                    f"them MUST be uniqIf(col, col != ''); a bare uniq() would count '' as a real "
                    f"identity. Disconnected event types: "
                    f"{', '.join(s.disconnected_event_types) or 'none'}."
                ),
                "formula": "",
                "refs": sorted({proposal.table_name, *s.partial_identity_columns}),
                "source": "instrumentation_agent",
                "source_ref": f"DDLProposal:{proposal.table_name}",
                "status": "open",
                "confidence": 1.0,
            }
        )
    return entries


_KIND_ORDER = [
    "business_def",
    "entity",
    "metric",
    "relationship",
    "table_doc",
    "column_doc",
    "known_issue",
    "gap",
    "contradiction",
]


def _render_context(
    version: int,
    snapshot_id: str,
    fingerprint: str,
    entries: Sequence[ContextEntry],
    contradictions: Sequence[dict[str, Any]],
    disputed: set[str],
) -> str:
    formulas: dict[str, str] = {}
    lines = [
        f"# Atlys context layer — v{version}",
        "",
        "> **Generated file. Do not edit.** The ClickHouse tables `context_entry_log`, "
        "`context_snapshot`, `context_changelog` and `contradiction` are the source of truth; "
        "this markdown is a render of them. To change the context, write an entry.",
        "",
        f"- context version: **{version}**",
        f"- snapshot id: `{snapshot_id}`",
        f"- schema fingerprint: `{fingerprint[:32]}`",
        f"- entries: **{len(entries)}**",
        f"- contradictions recorded: **{len(contradictions)}** "
        f"({sum(1 for c in contradictions if c.get('verified'))} verified by an executed query)",
        f"- rendered at: {datetime.now().isoformat(timespec='seconds')}",
        "",
    ]
    by_kind: dict[str, list[ContextEntry]] = {}
    for e in entries:
        by_kind.setdefault(e.kind, []).append(e)
    for kind in _KIND_ORDER + sorted(set(by_kind) - set(_KIND_ORDER)):
        group = by_kind.get(kind)
        if not group:
            continue
        lines.append(f"## {kind} ({len(group)})")
        lines.append("")
        for e in sorted(group, key=lambda x: x.entry_id):
            flag = " **[DISPUTED]**" if e.entry_id in disputed else ""
            lines.append(f"### `{e.entry_id}` @v{e.version}{flag}")
            lines.append("")
            lines.append(f"**{e.key}**")
            lines.append("")
            lines.append(e.body)
            meta = [f"source: `{e.source}`", f"status: `{e.status}`", f"confidence: {e.confidence:g}"]
            if e.refs:
                meta.append("refs: " + ", ".join(f"`{r}`" for r in e.refs[:12]))
            lines.append("")
            lines.append("<sub>" + " · ".join(meta) + "</sub>")
            lines.append("")
    if contradictions:
        lines.append("## Contradictions — the LLM proposes, SQL adjudicates")
        lines.append("")
        for c in contradictions:
            mark = "✅ verified" if c.get("verified") else "⚠️ unverified"
            lines.append(f"### [{c['kind']}] {c['title']}  ({c['severity']}, {mark})")
            lines.append("")
            lines.append(f"- **Context claims:** {c['claim']}")
            lines.append(f"- **Reality says:** {c['evidence']}")
            lines.append(f"- **Proposed resolution:** {c['proposed_resolution']}")
            if c.get("entry_ids"):
                lines.append("- **Entries:** " + ", ".join(f"`{e}`" for e in c["entry_ids"]))
            if c.get("verification_sql"):
                lines.append("")
                lines.append("```sql")
                lines.append(c["verification_sql"])
                lines.append("```")
                lines.append("")
                lines.append(f"Executed result: `{c.get('verification_result', '')}`")
            lines.append("")
    return "\n".join(lines) + "\n"


def _render_changelog(
    rows: Sequence[dict[str, Any]], snapshots: Sequence[dict[str, Any]]
) -> str:
    lines = [
        "# Context layer changelog",
        "",
        "> Generated from `context_changelog` and `context_snapshot`. Every line is an "
        "append-only fact about how the context moved.",
        "",
        "## Versions",
        "",
        "| version | snapshot id | entries | schema fingerprint | note | run_id |",
        "|---|---|---|---|---|---|",
    ]
    for s in snapshots:
        lines.append(
            f"| v{s['version']} | `{s['snapshot_id']}` | {s['entry_count']} | "
            f"`{str(s.get('schema_fingerprint') or '')[:12]}` | {s.get('note', '')} | "
            f"`{str(s.get('run_id') or '')[:8]}` |"
        )
    lines += ["", "## Entry history", ""]
    current_run = object()
    for r in rows:
        if r["run_id"] != current_run:
            current_run = r["run_id"]
            lines.append("")
            lines.append(f"### run `{str(current_run)[:12] or 'n/a'}` — {r['ts']}")
            lines.append("")
        arrow = f"v{r['from_version']} → v{r['to_version']}" if r["from_version"] else f"v{r['to_version']}"
        lines.append(f"- **{r['action']}** `{r['entry_id']}` ({arrow}) — {r['summary']}")
        if r.get("detail"):
            lines.append(f"  - {r['detail']}")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# module-level API (the signatures the pipeline codes against)
# --------------------------------------------------------------------------


def bootstrap(base_context_md: str | Path = DEFAULT_BASE_CONTEXT, ch: Any = None, run_id: str = "") -> int:
    ch = ch or _default_ch()
    return ContextAgent(ch, run_id=run_id).bootstrap(base_context_md)


def snapshot(ch: Any = None, run_id: str = "", note: str = "") -> ContextSnapshot:
    ch = ch or _default_ch()
    return ContextAgent(ch, run_id=run_id).snapshot(note=note)


def reconcile(
    ch: Any = None,
    new_tables: Sequence[str] = (),
    proposal: DDLProposal | None = None,
    run_id: str = "",
    note: str = "",
    use_llm: bool = False,
) -> ContextDiff:
    ch = ch or _default_ch()
    return ContextAgent(ch, run_id=run_id).reconcile(
        new_tables, proposal, note=note, use_llm=use_llm
    )


def render_markdown(ch: Any = None, out_dir: str | Path = DEFAULT_OUT_DIR, run_id: str = "") -> dict[str, Path]:
    ch = ch or _default_ch()
    return ContextAgent(ch, run_id=run_id).render_markdown(out_dir)


def _default_ch() -> Any:
    from ch import CH

    return CH()
