#!/usr/bin/env bash
# The two numbers the pitch rests on, re-derived from the current data and committed.
#
#   ./scripts/measure_divergence.sh [csv]
#
# 1. naive session-span vs foreground-only: the overcount this project exists to prevent.
#    Phantom minutes are counted by the literal predicate (naive > 0 AND corrected = 0),
#    not by subtracting two totals: those agree only if the corrected minutes are a subset
#    of the naive ones, which is likely and unproven. If they disagree, that is a finding.
#
# 2. AdPause / AdResume: measured by running the oracle twice, once with the ad-pause family
#    classified (current behaviour) and once with it neutral. The variant is generated by
#    deleting the two literals from the query, so both runs share every other rule.
set -euo pipefail
cd "$(dirname "$0")/.."
. scripts/lib/evidence.sh

CSV="${1:-data/ch-hackathon-raw-data.csv}"
TOL="${TOLERANCE_S:-90}"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

oracle() { FORMAT=TSV TOLERANCE_S="$TOL" PAUSE_INACTIVE="${1:-1}" \
             ./scripts/oracle.sh "$CSV" "$2" 2>/dev/null; }

echo "== naive session-span"
oracle 1 sql/queries/validation/naive_session_overlap.sql | sort > "$TMP/naive.tsv"
echo "== foreground-only oracle"
oracle 1 sql/queries/validation/oracle_concurrency.sql | cut -f1,2 | sort > "$TMP/corrected.tsv"

awk -F'\t' '
  NR==FNR { naive[$1]=$2; if ($2+0 > pn) { pn=$2+0; pnm=$1 } ; if ($2+0>0) nmin++; next }
  { corr[$1]=$2; if ($2+0 > pc) { pc=$2+0; pcm=$1 }; if ($2+0>0) cmin++ }
  END {
    for (m in naive) if (naive[m]+0 > 0 && corr[m]+0 == 0) phantom++
    for (m in corr)  if (corr[m]+0 > 0 && naive[m]+0 == 0) inverted++
    printf "metric\tvalue\n"
    printf "peak_naive\t%d\n", pn
    printf "peak_naive_minute\t%s\n", pnm
    printf "peak_corrected\t%d\n", pc
    printf "peak_corrected_minute\t%s\n", pcm
    printf "overcount_pct_at_peak\t%.1f\n", (pn-pc)*100.0/pc
    printf "minutes_naive_gt0\t%d\n", nmin
    printf "minutes_corrected_gt0\t%d\n", cmin
    printf "phantom_minutes_predicate\t%d\n", phantom+0
    printf "phantom_minutes_subtraction\t%d\n", nmin-cmin
    printf "inverted_minutes_corrected_gt0_naive_eq0\t%d\n", inverted+0
  }' "$TMP/naive.tsv" "$TMP/corrected.tsv" \
  | evidence naive_vs_foreground "naive session-span vs foreground-only oracle, tolerance_s=$TOL" \
  | xargs cat

echo
echo "== AdPause / AdResume impact"
# ponytail: sed the two literals out rather than adding a third parameter to the oracle.
# The diff between the files is the entire experiment and is visible in one command.
sed -e "s/, 'AdPause'//" -e "s/, 'AdResume'//" \
    sql/queries/validation/oracle_concurrency.sql > "$TMP/oracle_no_ad.sql"
# grep -c exits 1 on zero matches, and pipefail would read that as the guard failing
[ "$(grep -c "AdPause\|AdResume" "$TMP/oracle_no_ad.sql" || true)" = 0 ] \
  || { echo "variant still mentions the ad family, refusing to report" >&2; exit 1; }

oracle 1 "$TMP/oracle_no_ad.sql" | cut -f1,2 | sort > "$TMP/no_ad.tsv"

awk -F'\t' '
  NR==FNR { with[$1]=$2; if ($2+0>pw) pw=$2+0; if ($2+0>0) wmin++; next }
  { if ($2+0>pn) pn=$2+0; if ($2+0>0) nmin++
    if (with[$1]+0 != $2+0) { d++
      v = ($2+0)-(with[$1]+0); if (v < 0) v = -v          # magnitude, either direction
      if (v > mx) mx = v } }
  END {
    printf "metric\tvalue\n"
    printf "peak_ad_family_classified\t%d\n", pw
    printf "peak_ad_family_neutral\t%d\n", pn
    printf "peak_delta\t%d\n", pn-pw
    printf "minutes_with_audience_classified\t%d\n", wmin
    printf "minutes_with_audience_neutral\t%d\n", nmin
    printf "minutes_differing\t%d\n", d+0
    printf "max_per_minute_delta\t%d\n", mx+0
  }' "$TMP/corrected.tsv" "$TMP/no_ad.tsv" \
  | evidence adpause_impact "oracle with AdPause/AdResume classified vs neutral, tolerance_s=$TOL" \
  | xargs cat
