#!/usr/bin/env bash
# Generate PUSHLOG.md — a human-readable record of everything that landed on `main`:
# per commit, the summary, author, date, and the files changed. Derived from git history, so
# it is always accurate and can never silently miss a push.
#
#   bash scripts/pushlog.sh          # regenerate PUSHLOG.md (preview locally)
# The GitHub Action (.github/workflows/pushlog.yml) runs this on every push to main and commits
# the result, so the committed PUSHLOG.md stays current with zero manual effort.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
OUT="${1:-PUSHLOG.md}"
BR="${2:-main}"

{
  echo "# Push Log"
  echo
  echo "Everything that has landed on \`$BR\`, newest first — summary, author, date, and files changed."
  echo "**Auto-generated by \`scripts/pushlog.sh\`; do not edit by hand.** Use it to review what we"
  echo "shipped and to spot anything pushed by mistake."
  echo
  # --first-parent: each squash-merged PR shows as ONE entry, not its internal commits
  git log --first-parent "$BR" --date=format:'%Y-%m-%d %H:%M' \
      --pretty=format:'%H%x1f%h%x1f%ad%x1f%an%x1f%s' |
  while IFS=$'\x1f' read -r full short date author subject; do
    case "$subject" in "chore: update PUSHLOG"*) continue ;; esac  # skip the log-bot's own commits
    echo "### \`$short\` — $subject"
    echo "*$date · $author*"
    echo
    echo '```'
    git show "$full" --stat --format='' | sed '/^[[:space:]]*$/d'
    echo '```'
    echo
  done
} > "$OUT"
echo "wrote $OUT ($(git rev-list --count "$BR") commits on $BR)"
