"""Generate `docs/SCHEMA_CATALOG.md` from the LIVE database.

    python -m tools.schema_catalog            # writes docs/SCHEMA_CATALOG.md
    python -m tools.schema_catalog --stdout   # print instead

Read-only: `system.tables`, `system.columns`, `system.merge_tree_settings`, plus the
`artifacts/runs/*/proposal.json` files the pipeline already wrote. Nothing here queries
feature data, and nothing is hand-maintained -- a catalog that drifts from the database
is worse than none, so it is generated on demand rather than written down.

The section that earns its place is "Materialized views considered and rejected".
Every schema doc lists what was built; almost none list what was proposed, measured and
then DROPPED with the number that killed it. That record already exists in each run's
`proposal.json` (`reduction_factor`, `kept`) because MVs are kept or dropped on a
measured reduction rather than on faith -- this just surfaces it.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent.parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from ch import CH  # noqa: E402

ARTIFACT_RUNS = HERE / "artifacts" / "runs"
OUT = HERE / "docs" / "SCHEMA_CATALOG.md"


def _tables(ch: CH) -> list[dict[str, Any]]:
    return ch.run_select(
        "SELECT name, engine, total_rows, total_bytes, sorting_key, partition_key, "
        "primary_key, create_table_query "
        "FROM system.tables WHERE database = currentDatabase() "
        "ORDER BY engine, name",
        max_rows=500,
    )


def _columns(ch: CH) -> dict[str, list[dict[str, Any]]]:
    rows = ch.run_select(
        "SELECT table, name, type, comment, is_in_partition_key, is_in_sorting_key, "
        "default_kind, default_expression "
        "FROM system.columns WHERE database = currentDatabase() "
        "ORDER BY table, position",
        max_rows=5000,
    )
    by: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for r in rows:
        by[str(r["table"])].append(r)
    return by


def _changed_settings(ch: CH) -> list[dict[str, Any]]:
    try:
        return ch.run_select(
            "SELECT name, value, description FROM system.merge_tree_settings "
            "WHERE changed = 1 ORDER BY name",
            max_rows=200,
        )
    except Exception:  # noqa: BLE001 - older/newer servers vary here; not worth failing over
        return []


def _mv_decisions() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """(kept, rejected) MV decisions across every recorded run."""
    kept: list[dict[str, Any]] = []
    rejected: list[dict[str, Any]] = []
    if not ARTIFACT_RUNS.exists():
        return kept, rejected
    for proposal in sorted(ARTIFACT_RUNS.glob("*/proposal.json")):
        try:
            data = json.loads(proposal.read_text(encoding="utf-8"))
        except Exception:  # noqa: BLE001
            continue
        run_id = proposal.parent.name
        for mv in data.get("materialized_views") or []:
            row = {
                "run_id": run_id,
                "table": data.get("table_name", "?"),
                "name": mv.get("name", "?"),
                "target": mv.get("target_table", "?"),
                "reduction": mv.get("reduction_factor"),
                "src": mv.get("measured_source_rows"),
                "dst": mv.get("measured_target_rows"),
                "why": (mv.get("justification") or "").replace("\n", " ")[:180],
            }
            (kept if mv.get("kept") else rejected).append(row)
    return kept, rejected


def _fmt(n: Any) -> str:
    try:
        return f"{int(n):,}"
    except (TypeError, ValueError):
        return "—"


def render(ch: CH) -> str:
    tables = _tables(ch)
    cols = _columns(ch)
    kept, rejected = _mv_decisions()
    version = ch.run_select("SELECT version() AS v")[0]["v"]

    out: list[str] = [
        "# Schema catalog",
        "",
        "> Generated by `make schema-doc` (`tools/schema_catalog.py`) from the live "
        "database. Do not edit by hand — regenerate it. Every figure below is read from "
        f"`system.*` at generation time. ClickHouse `{version}`, database "
        f"`{ch.database}`.",
        "",
        f"{len(tables)} objects, {sum(len(v) for v in cols.values())} columns.",
        "",
        "## Contents",
        "",
        "- [Objects](#objects)",
        "- [Materialized views: kept](#materialized-views-kept)",
        "- [Materialized views: considered and rejected](#materialized-views-considered-and-rejected)",
        "- [Non-default MergeTree settings](#non-default-mergetree-settings)",
        "",
        "## Objects",
        "",
        "| Table | Engine | Rows | Bytes | Sorting key |",
        "| --- | --- | ---: | ---: | --- |",
    ]
    for t in tables:
        out.append(
            f"| `{t['name']}` | {t['engine']} | {_fmt(t['total_rows'])} | "
            f"{_fmt(t['total_bytes'])} | `{t['sorting_key'] or '—'}` |"
        )
    out.append("")

    for t in tables:
        name = str(t["name"])
        out += [f"### `{name}`", ""]
        meta = [f"**Engine** `{t['engine']}`"]
        if t["partition_key"]:
            meta.append(f"**Partition by** `{t['partition_key']}`")
        if t["sorting_key"]:
            meta.append(f"**Order by** `{t['sorting_key']}`")
        out += [" · ".join(meta), ""]
        tcols = cols.get(name, [])
        if tcols:
            out += [
                "| Column | Type | Key | Default | Comment |",
                "| --- | --- | --- | --- | --- |",
            ]
            for c in tcols:
                flags = []
                if c["is_in_sorting_key"]:
                    flags.append("sort")
                if c["is_in_partition_key"]:
                    flags.append("part")
                default = (
                    f"`{c['default_kind']} {c['default_expression']}`".strip()
                    if c["default_kind"] else "—"
                )
                comment = (str(c["comment"] or "—").replace("|", "\\|").replace("\n", " "))[:220]
                out.append(
                    f"| `{c['name']}` | `{c['type']}` | {','.join(flags) or '—'} | "
                    f"{default} | {comment} |"
                )
            out.append("")

    out += ["## Materialized views: kept", ""]
    if not kept:
        out += ["_None recorded._", ""]
    else:
        out += ["| MV | Source table | Target | Measured reduction | Rows |", "| --- | --- | --- | ---: | --- |"]
        for m in kept:
            r = f"{m['reduction']}x" if m["reduction"] is not None else "not measured"
            out.append(
                f"| `{m['name']}` | `{m['table']}` | `{m['target']}` | {r} | "
                f"{_fmt(m['src'])} → {_fmt(m['dst'])} |"
            )
        out.append("")

    out += [
        "## Materialized views: considered and rejected",
        "",
        "An MV is kept or dropped on a **measured** reduction factor, not on faith: the "
        "pipeline builds it, loads the data, counts both sides, and drops it if it does "
        "not earn its keep. Those rejections are recorded here rather than quietly "
        "forgotten — a schema doc that only lists what survived hides the reasoning.",
        "",
    ]
    if not rejected:
        out += ["_No MV has been proposed and rejected in any recorded run._", ""]
    else:
        out += [
            "| MV (dropped) | Source table | Measured reduction | Rows | Run |",
            "| --- | --- | ---: | --- | --- |",
        ]
        for m in rejected:
            r = f"{m['reduction']}x" if m["reduction"] is not None else "not measured"
            out.append(
                f"| `{m['name']}` | `{m['table']}` | {r} | {_fmt(m['src'])} → "
                f"{_fmt(m['dst'])} | `{m['run_id'][:12]}` |"
            )
        out.append("")

    settings = _changed_settings(ch)
    out += ["## Non-default MergeTree settings", ""]
    if not settings:
        out += ["_All MergeTree settings are at their server defaults._", ""]
    else:
        out += ["| Setting | Value |", "| --- | --- |"]
        for s in settings:
            out.append(f"| `{s['name']}` | `{s['value']}` |")
        out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--stdout", action="store_true", help="print instead of writing the file")
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args(argv)

    text = render(CH())
    if args.stdout:
        print(text)
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out} ({len(text):,} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
