import useSWR from "swr";
import type { Investigation } from "@/types";

// Live API first, bundled snapshot second.
//
// The snapshot is NOT hand-authored — it is a verbatim copy of a real
// ./investigate.sh run, regenerated by `npm run refresh-fixture`. That matters
// more here than in most projects: this system's entire claim is that every
// number on screen was computed from the data, so a plausible-looking
// hand-written fixture would be the one thing capable of putting a fabricated
// figure in front of a reader.
//
// The fallback exists so the UI still renders if the API is down mid-demo, and
// `usingFallback` is surfaced in the UI so nobody can mistake a cached run for
// a live one.
const API_URL = `${import.meta.env.VITE_API_URL ?? "http://localhost:8010"}/api/v1/investigation`;
// Resolved against the deployed base, not the domain root — an absolute
// "/diagnosis.json" 404s on any subpath deployment.
const SNAPSHOT_URL = `${import.meta.env.BASE_URL}diagnosis.json`;

async function fetchInvestigation(): Promise<{
  investigation: Investigation;
  usingFallback: boolean;
}> {
  try {
    const res = await fetch(API_URL, { signal: AbortSignal.timeout(4000) });
    if (res.ok) {
      return { investigation: (await res.json()) as Investigation, usingFallback: false };
    }
  } catch {
    // API unreachable — fall through to the bundled snapshot.
  }
  const res = await fetch(SNAPSHOT_URL);
  if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
  return { investigation: (await res.json()) as Investigation, usingFallback: true };
}

export function useInvestigation() {
  const { data, error, isLoading } = useSWR("investigation", fetchInvestigation, {
    revalidateOnFocus: false,
  });
  return {
    investigation: data?.investigation,
    usingFallback: data?.usingFallback ?? false,
    error,
    isLoading,
  };
}
