#!/usr/bin/env bash
# Derive librechat/.env from the root .env (CLICKHOUSE_DSN + LLM keys).
# Run once before: docker compose --profile chat up -d
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="${ROOT}/librechat/.env"

if [[ -f "${ROOT}/.env" ]]; then
  # shellcheck disable=SC1091
  set -a && source "${ROOT}/.env" && set +a
fi
# Merge Langfuse keys from generated librechat env when absent in root .env.
if [[ -f "${ROOT}/librechat/.env" ]]; then
  # shellcheck disable=SC1091
  set -a && source "${ROOT}/librechat/.env" && set +a
fi

# macOS: export keychain CAs so LiteLLM container can reach Langfuse Cloud over TLS.
if [[ "$(uname -s)" == "Darwin" ]] && [[ -n "${LANGFUSE_PUBLIC_KEY:-}" || -n "${LANGFUSE_SECRET_KEY:-}" ]]; then
  "${ROOT}/clickhouse/scripts/export_macos_certs.sh" || true
fi

if [[ -z "${CLICKHOUSE_DSN:-}" ]]; then
  echo "CLICKHOUSE_DSN not set in ${ROOT}/.env" >&2
  exit 1
fi

python3 - "$CLICKHOUSE_DSN" "$OUT" <<'PY'
import sys, os
from urllib.parse import urlparse, unquote

dsn = sys.argv[1].replace("clickhouse://", "http://", 1)
out = sys.argv[2]
u = urlparse(dsn)
host = u.hostname or ""
port = u.port or 9440
user = unquote(u.username or "default")
password = unquote(u.password or "")
db = (u.path or "/sony_liv").lstrip("/") or "sony_liv"
# Pulse serving tables live in sony_liv even when admin DSN path is /default.
if db == "default":
    db = os.environ.get("LIBRECHAT_CH_DATABASE", "sony_liv")
else:
    db = os.environ.get("LIBRECHAT_CH_DATABASE", db)
q = dict(p.split("=", 1) for p in u.query.split("&") if "=" in p)
secure = q.get("secure", "true" if str(port) in ("9440", "8443") else "false")

# MCP uses HTTPS port on Cloud; readonly user is separate from admin DSN.
ro_user = os.environ.get("LIBRECHAT_CH_USER", "pulse_readonly")
ro_pass = os.environ.get("LIBRECHAT_CH_PASSWORD", "Pulse_ro_demo_2026")
mcp_port = os.environ.get("LIBRECHAT_CH_PORT", "8443")

litellm_key = (
    os.environ.get("LITELLM_API_KEY")
    or os.environ.get("LITELLM_MASTER_KEY")
    or os.environ.get("ANTHROPIC_API_KEY", "")
)
langfuse_host = os.environ.get("LANGFUSE_HOST") or os.environ.get("LANGFUSE_BASE_URL", "https://cloud.langfuse.com")
upstream = os.environ.get("LITELLM_UPSTREAM_URL") or os.environ.get("LITELLM_BASE_URL", "")
# When Langfuse is configured, LibreChat uses the in-compose traced LiteLLM proxy.
if os.environ.get("LANGFUSE_PUBLIC_KEY") and os.environ.get("LANGFUSE_SECRET_KEY"):
    litellm_base = os.environ.get("LITELLM_PROXY_URL", "http://litellm:4000/v1")
else:
    litellm_base = os.environ.get("LITELLM_BASE_URL", upstream)

lines = [
    "# Generated by clickhouse/scripts/sync_librechat_env.sh — edit LLM keys in root .env",
    f"CH_HOST={host}",
    f"CH_PORT={mcp_port}",
    f"CH_USER={ro_user}",
    f"CH_PASSWORD={ro_pass}",
    f"CH_SECURE={'true' if secure == 'true' else 'false'}",
    f"CH_DATABASE={db}",
    "",
    f"CLICKHOUSE_HOST={host}",
    f"CLICKHOUSE_PORT={mcp_port}",
    f"CLICKHOUSE_USER={ro_user}",
    f"CLICKHOUSE_PASSWORD={ro_pass}",
    f"CLICKHOUSE_SECURE={'true' if secure == 'true' else 'false'}",
    f"CLICKHOUSE_DATABASE={db}",
    "",
    f"LIBRECHAT_CH_HOST={host}",
    f"LIBRECHAT_CH_PORT={mcp_port}",
    f"LIBRECHAT_CH_USER={ro_user}",
    f"LIBRECHAT_CH_PASSWORD={ro_pass}",
    f"LIBRECHAT_CH_SECURE={'true' if secure == 'true' else 'false'}",
    f"LIBRECHAT_CH_DATABASE={db}",
    "",
    f"OPENAI_API_KEY={os.environ.get('OPENAI_API_KEY', '')}",
    f"ANTHROPIC_API_KEY={os.environ.get('ANTHROPIC_API_KEY', '')}",
    "",
    "# LiteLLM — traced proxy when Langfuse keys present",
    f"LITELLM_UPSTREAM_URL={upstream}",
    f"LITELLM_PROXY_URL={os.environ.get('LITELLM_PROXY_URL', 'http://litellm:4000/v1')}",
    "",
    "# Langfuse (LLM traces)",
    f"LANGFUSE_PUBLIC_KEY={os.environ.get('LANGFUSE_PUBLIC_KEY', '')}",
    f"LANGFUSE_SECRET_KEY={os.environ.get('LANGFUSE_SECRET_KEY', '')}",
    f"LANGFUSE_HOST={langfuse_host}",
    f"LANGFUSE_BASE_URL={langfuse_host}",
    f"LANGFUSE_TRACING_ENVIRONMENT={os.environ.get('LANGFUSE_TRACING_ENVIRONMENT', 'development')}",
    "",
    # LibreChat auth — must be 32-byte hex (see librechat.ai/docs/configuration/dotenv)
    "JWT_SECRET=16f8c0ef4a5d391b26034086c628469d3f9f497f08163ab9b40137092f2909ef",
    "JWT_REFRESH_SECRET=eaa5191f2914e30b9387fd84e254e4ba6fc51b4654968a9b0803b456a54b8418",
    "CREDS_KEY=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
    "CREDS_IV=0123456789abcdef0123456789abcdef",
    "",
    "# Admin DSN (for reference — MCP uses readonly creds above)",
    f"# CLICKHOUSE_DSN host={host} db={db} admin_user={user}",
]
open(out, "w").write("\n".join(lines) + "\n")
print(f"wrote {out}")
print(f"  CH_HOST={host} CH_PORT={mcp_port} CH_USER={ro_user} CH_DATABASE={db}")

# ClickStack Cloud collector (OTLP → ClickHouse Cloud)
obs_out = os.path.join(os.path.dirname(out), "..", "observability.env")
obs_lines = [
    "# Generated by clickhouse/scripts/sync_librechat_env.sh",
    f"CLICKHOUSE_ENDPOINT=https://{host}:8443",
    f"CLICKHOUSE_USER={user}",
    f"CLICKHOUSE_PASSWORD={password}",
]
open(obs_out, "w").write("\n".join(obs_lines) + "\n")
print(f"wrote {obs_out}")

# librechat.yaml leaves ${LITELLM_BASE_URL} — LibreChat does not always expand
# baseURL from env; bake the URL into a gitignored runtime config.
root = os.path.join(os.path.dirname(out), "..")
template_path = os.path.join(root, "librechat", "librechat.yaml")
runtime_path = os.path.join(root, "librechat", "librechat.runtime.yaml")
if not litellm_base:
    print("warn: LITELLM_BASE_URL unset — LiteLLM models will not load", file=sys.stderr)
else:
    tpl = open(template_path).read()
    runtime = tpl.replace("${LITELLM_BASE_URL}", litellm_base)
    open(runtime_path, "w").write(runtime)
    print(f"wrote {runtime_path} (baseURL={litellm_base})")
PY

# Also export for docker compose (same shell session).
# shellcheck disable=SC1091
set -a && source "$OUT" && set +a
echo "Run readonly user DDL if not done:"
echo "  cd ${ROOT}/backend && go run ./cmd/pipeline -dsn \"\$CLICKHOUSE_DSN\" -exec \"\$(cat ${ROOT}/clickhouse/scripts/create_readonly_user.sql)\""
