-- =============================================================================
-- Atlys ClickHouse schema — generated by the Instrumentation Agent
-- -----------------------------------------------------------------------------
-- spec_name      : 08_destination_card_clicked
-- source ndjson  : /app/specs/08_destination_card_clicked/events.ndjson
-- source spec    : /app/specs/08_destination_card_clicked/spec.md
-- database       : atlys
-- base table     : destination_card_clicked          (ONE table, single JSON `payload`)
-- event types    : destination_card_clicked          (discriminator: payload.event)
-- target         : ClickHouse Cloud (plain MergeTree -> Shared* engines; no Replicated/
--                  Distributed/storage_policy)
-- validated      : MCP validation gate (__val create/insert/assert/drop) + live Cloud
--                  smoke test (base insert -> MV auto-fire -> AggregatingMergeTree merge-read
--                  with select_sequential_consistency = 1) — all green.
-- -----------------------------------------------------------------------------
-- Design decisions & best-practice citations
--   * schema-json-when-to-use        : one JSON column `payload` absorbs the full envelope +
--                                       spec fields; only ORDER BY / PARTITION BY / skip-indexed
--                                       paths are typed via the payload(...) hint.
--   * schema-pk-cardinality-order    : ORDER BY (payload.event, payload.destination,
--                                       payload.visa_type, payload.user_id, payload.timestamp)
--                                       — discriminator -> low-card frequent dims -> identity
--                                       -> event time last. application_id EXCLUDED (empty ""
--                                       on ~85% of rows).
--   * schema-partition-lifecycle     : PARTITION BY toYYYYMMDD(ch_insert_time); TTL 90d DELETE
--                                       on ch_insert_time; ttl_only_drop_parts = 1.
--
-- DEVIATIONS from atlys-schema-design (deliberate, validated):
--   [D1] Skip-indexed JSON paths are TYPED in the payload(...) hint (not just ORDER BY paths).
--        Data-skipping indexes (minmax/set/bloom_filter) on a dynamic JSON sub-column fail with
--        `Code: 36` unless the underlying path has a concrete type. So the hint types the
--        discriminator + ORDER BY paths + every skip-indexed path.
--   [D2] The rollup (AggregatingMergeTree) TTL keys on an INGEST/COMPUTE timestamp
--        (agg_insert_time DEFAULT now64(3)), NOT on the event date `day`. Keying retention on a
--        historical event date silently TTL-deletes back-filled rollups on the next merge
--        (server clock ran ~197 days ahead of the test event dates). agg_insert_time is NOT in
--        the ORDER BY — it is a retention anchor only, mirroring the base table's ch_insert_time.
-- =============================================================================

CREATE DATABASE IF NOT EXISTS atlys;

-- -----------------------------------------------------------------------------
-- Base table — one row per destination_card_clicked event, full payload retained
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS atlys.destination_card_clicked
(
    `payload` JSON(
        `event`               LowCardinality(String),
        `user_id`             String,
        `timestamp`           DateTime64(3, 'UTC'),
        `destination`         LowCardinality(String),
        `visa_type`           LowCardinality(String),
        -- skip-indexed paths must be typed [D1]
        `page_version`        LowCardinality(String),
        `flow`                LowCardinality(String),
        `device_type`         LowCardinality(String),
        `os`                  LowCardinality(String),
        `geoip_country_code`  LowCardinality(String),
        `is_guest_browse`     UInt8
    ),
    `ch_insert_time` DateTime64(3, 'UTC') MATERIALIZED now64(3) CODEC(Delta(8), ZSTD(1)),

    -- Data-skipping indexes on hot filter paths NOT in the ORDER BY [D1]
    INDEX idx_page_version  payload.page_version       TYPE set(8)             GRANULARITY 1,
    INDEX idx_flow          payload.flow               TYPE set(16)            GRANULARITY 1,
    INDEX idx_guest_browse  payload.is_guest_browse    TYPE minmax             GRANULARITY 1,
    INDEX idx_device_type   payload.device_type        TYPE set(32)            GRANULARITY 1,
    INDEX idx_os            payload.os                 TYPE set(32)            GRANULARITY 1,
    INDEX idx_geoip_cc      payload.geoip_country_code TYPE bloom_filter(0.01) GRANULARITY 1
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(ch_insert_time)
ORDER BY (payload.event, payload.destination, payload.visa_type, payload.user_id, payload.timestamp)
TTL toDateTime(ch_insert_time) + INTERVAL 90 DAY DELETE
SETTINGS index_granularity = 16384, ttl_only_drop_parts = 1;

-- -----------------------------------------------------------------------------
-- Rollup: daily destination-click metrics (single-table, incremental)
--   Serves PM Q3 (share of is_guest_browse=1 clicks) and Q5 (co_travelers/destination
--   volume) plus general click volume by destination / visa_type / page_version / flow.
--   Cross-event conversion metrics (Q1, Q2, Q4, and the conversion halves of Q3/Q5) are
--   NOT served here — they join spec 10_application_started and are left to query time.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS atlys.destination_click_daily_agg
(
    `day`             Date,
    `destination`     LowCardinality(String),
    `visa_type`       LowCardinality(String),
    `page_version`    LowCardinality(String),
    `flow`            LowCardinality(String),
    `clicks`          AggregateFunction(count),
    `guest_clicks`    AggregateFunction(sum, UInt64),
    `unique_users`    AggregateFunction(uniq, String),
    -- retention anchored on compute time, NOT event date [D2]
    `agg_insert_time` DateTime64(3, 'UTC') DEFAULT now64(3) CODEC(Delta(8), ZSTD(1))
)
ENGINE = AggregatingMergeTree
PARTITION BY toYYYYMM(day)
ORDER BY (day, destination, visa_type, page_version, flow)
TTL toDateTime(agg_insert_time) + INTERVAL 90 DAY DELETE
SETTINGS index_granularity = 16384, ttl_only_drop_parts = 1;

CREATE MATERIALIZED VIEW IF NOT EXISTS atlys.destination_click_daily_agg_mv
TO atlys.destination_click_daily_agg
AS
SELECT
    toDate(payload.timestamp)                        AS day,
    CAST(payload.destination  AS String)             AS destination,
    CAST(payload.visa_type    AS String)             AS visa_type,
    CAST(payload.page_version AS String)             AS page_version,
    CAST(payload.flow         AS String)             AS flow,
    countState()                                     AS clicks,
    sumState(toUInt64(payload.is_guest_browse = 1))  AS guest_clicks,
    uniqState(CAST(payload.user_id AS String))       AS unique_users
FROM atlys.destination_card_clicked
WHERE CAST(payload.event AS String) = 'destination_card_clicked'
GROUP BY day, destination, visa_type, page_version, flow;
