-- ============================================================================
-- 01_policy.sql — THE POLICY, AS SQL SEES IT.
--
-- GENERATED by tools/policy.sh gen from policy/model.policy. DO NOT EDIT: the
-- declaration is policy/model.policy, this file is a rendering of it, and
-- `tools/policy.sh check` fails the build if the two disagree.
--
-- Why a view and not a table: a view is DDL, so applying it is non-destructive
-- and per-database — the graded database and a scratch database can hold
-- different policies without one silently rewriting the other (a server-wide
-- SQL UDF could not give that). A missing view is a LOUD error at query time,
-- where a missing row in a key/value table would resolve to a default and give
-- you GAP_S = 0 without a word.
--
-- Consumers read it as scalar subqueries:
--     WITH (SELECT gap_s FROM v_model_policy) AS GAP_S
-- which ClickHouse folds to a constant, so it is free inside a lambda.
--
-- policy version 1, content hash e965954b23d4
-- ADR 0032 · inventory docs/DYNAMIC_PARAMS.md · sensitivity evidence/params/
-- ============================================================================

CREATE OR REPLACE VIEW v_model_policy AS
SELECT
    'e965954b23d4'                                 AS policy_hash,
    '1'                                            AS policy_version,
    toUInt32(150)                                  AS gap_s,
    toUInt32(60)                                   AS tail_s,
    toUInt8(1)                                     AS unclosed_pause_to_run_end,
    toUInt8(0)                                     AS point_activity_counts,
    toUInt32(5)                                    AS publish_settle_s,
    toUInt32(900)                                  AS publish_lookback_s,
    toUInt32(60)                                   AS publish_lease_ttl_s,
    toUInt32(2)                                    AS publish_lease_settle_s,
    toUInt32(240)                                  AS publish_minute_cover_s,
    toUInt32(7200)                                 AS publish_hour_cover_s,
    toUInt32(300)                                  AS publish_interval_prefilter_s,
    toUInt16(7)                                    AS queue_ttl_days
;

-- Long form, for humans and for evidence. Derived FROM the wide view above,
-- never from the declaration a second time.
CREATE OR REPLACE VIEW v_model_policy_kv AS
SELECT p.1 AS tier, p.2 AS key, p.3 AS value, p.4 AS note
FROM
(
    SELECT arrayJoin([
        ('meta', 'policy_hash', policy_hash, 'sha256(sorted KEY=VALUE), first 12 hex'),
        ('meta', 'policy_version', toString(policy_version), ''),
        ('model', 'gap_s', toString(gap_s), 'a heartbeat gap STRICTLY GREATER than this ends an active run (s)'),
        ('model', 'tail_s', toString(tail_s), 'grace credited after the last event of a run (s)'),
        ('model', 'unclosed_pause_to_run_end', toString(unclosed_pause_to_run_end), '1 = a pause with no resume lasts to run end (conservative)'),
        ('model', 'point_activity_counts', toString(point_activity_counts), '1 = a zero-duration segment still earns one cadence'),
        ('publish', 'publish_settle_s', toString(publish_settle_s), 'assumed max seconds from now64(3) to full row visibility'),
        ('publish', 'publish_lookback_s', toString(publish_lookback_s), 'how far behind the committed cursor a claim re-scans'),
        ('publish', 'publish_lease_ttl_s', toString(publish_lease_ttl_s), 'how long a silent lease holder stays authoritative'),
        ('publish', 'publish_lease_settle_s', toString(publish_lease_settle_s), 'settle wait inside the lease acquisition lottery'),
        ('publish', 'publish_minute_cover_s', toString(publish_minute_cover_s), 'minutes(lo .. hi + this) is a superset of the batch''s touched minutes'),
        ('publish', 'publish_hour_cover_s', toString(publish_hour_cover_s), 'hours(lo .. hi + this) is a superset of the batch''s touched hours'),
        ('publish', 'publish_interval_prefilter_s', toString(publish_interval_prefilter_s), 'interval prefilter half-width around the batch window'),
        ('publish', 'queue_ttl_days', toString(queue_ttl_days), 'retention of session_dirty / cc_publish_batch / cc_publish_consumed')
    ]) AS p
    FROM v_model_policy
);
