import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ClickUIProvider, Title, Text, Button, Panel, Badge } from '@clickhouse/click-ui';
import './styles.css';

type Agent = { agent: string; status: string; progress: string; error_message: string };
type Investigation = { status: string; current_agent: string; progress: string; final_result: string; error_message: string; agents: Agent[] };
type RecordValue = Record<string, unknown>;

function App() { const match = location.pathname.match(/^\/investigations\/([^/]+)$/); return <ClickUIProvider theme="dark">{match ? <Status id={match[1]} /> : location.pathname === '/demo' ? <Demo /> : <Upload />}</ClickUIProvider>; }
function Shell({ children }: { children: React.ReactNode }) { return <div className="app-shell"><main><header><Text className="eyebrow">ATLYS · INTELLIGENCE STUDIO</Text><Title type="h1">From product signal<br />to confident action.</Title><Text className="lede">A decision-ready view of every feature: evidence, opportunities, and the next best move.</Text></header>{children}</main></div>; }

function Upload() {
  const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); setError(''); const response = await fetch('/api/investigations', { method: 'POST', body: new FormData(event.currentTarget) }); if (!response.ok) { setError((await response.json()).detail || 'Upload failed'); setSubmitting(false); return; } location.assign((await response.json()).status_url); }
  return <Shell><Panel className="content-card" padding="xl" hasBorder hasShadow><form onSubmit={submit}><div className="card-heading"><div><Text className="step">NEW PRODUCT REVIEW</Text><Title type="h2">Bring your feature to life</Title></div><Text className="secure">Private workspace</Text></div><Text className="card-description">Share the PRD and a representative event sample. Your agent team turns them into an evidence-backed launch plan.</Text><label className="feature-key"><span>Feature key</span><small>Stable across iterations; enables schema history, for example <code>express_checkout</code>.</small><input required name="feature_key" type="text" pattern="[a-z][a-z0-9_-]{0,63}" placeholder="express_checkout" /></label><div className="file-grid"><label><span>Event sample</span><small>events.ndjson</small><input required name="events" type="file" accept=".ndjson,application/x-ndjson" /></label><label><span>Feature brief</span><small>spec.md</small><input required name="spec" type="file" accept=".md,text/markdown" /></label></div>{error && <p className="error">{error}</p>}<Button className="submit-button" type="primary" htmlType="submit" disabled={submitting} fillWidth>{submitting ? 'Preparing your review…' : 'Create decision brief'}</Button></form></Panel></Shell>;
}

function object(value: unknown): RecordValue { return value && typeof value === 'object' && !Array.isArray(value) ? value as RecordValue : {}; }
function list(value: unknown): unknown[] { return Array.isArray(value) ? value : []; }
function text(value: unknown): string { return typeof value === 'string' || typeof value === 'number' ? String(value) : ''; }
function title(value: unknown, fallback: string) { const item = object(value); return text(item.title) || text(item.finding) || text(item.action) || text(item.text) || fallback; }
function detail(value: unknown) { const item = object(value); return text(item.description) || text(item.impact) || text(item.evidence) || text(item.detail) || ''; }
function traceMetrics(value: unknown) { const item = object(value); return [[item.duration_ms, 'ms'], [item.tool_calls, 'tools'], [item.tokens, 'tokens'], [item.cost, 'cost']].filter(([metric]) => text(metric)).map(([metric, unit]) => `${text(metric)} ${unit}`).join(' · '); }

function Demo() {
  const sample = { status: 'ready_for_delivery', feature: 'Express Checkout', metrics: [{ label: 'Confirmed orders', value: '836', detail: 'Evaluated pairs' }, { label: 'Amount match rate', value: '100%', detail: 'Verified aggregate' }, { label: 'Currency match rate', value: '100%', detail: 'Verified aggregate' }], executive_summary: ['Express Checkout has a clean amount/currency handoff across 836 confirmed orders.', 'The next highest-value move is to monitor checkout completion after launch while keeping amount consistency as a guardrail.'], insights: [{ finding: '100% of confirmed pairs have matching currency and amount.', impact: 'No observed pricing-data mismatch in the evaluated Express Checkout sample.', confidence: 'high' }], actions: { act_now: [{ action: 'Launch with amount-consistency monitoring', description: 'Keep the verified aggregate as a release guardrail; alert if either match rate drops below 99.5%.' }], investigate: [], instrument: [], monitor: [{ action: 'Monitor checkout conversion by device and payment method', description: 'Validate that consistent amounts translate into completed purchases after rollout.' }], no_action: [] }, dashboards: [{ title: 'Express Checkout consistency', hyperdx_url: 'https://app.hyperdx.io', description: 'Amount and currency match-rate monitor' }], data_quality: { status: 'trusted', issues: [] }, context: { version: 'context-1', contradictions: [] }, schema: { execution_status: 'validated', tables: [{ name: 'default.express_checkout_events' }] }, lineage: { trace_status: 'available', langfuse_trace_url: 'https://cloud.langfuse.com', stages: [{ agent: 'Instrumentation', status: 'completed', duration_ms: 1840 }, { agent: 'Analytics', status: 'completed', duration_ms: 2310 }, { agent: 'Context', status: 'completed', duration_ms: 620 }, { agent: 'Finalizer', status: 'completed', duration_ms: 430 }] }, limitations: ['Preview only: this is static example content and is not an investigation result.'], errors: [] };
  return <Shell><Panel className="content-card" padding="xl" hasBorder hasShadow><Text className="step">DESIGN PREVIEW · STATIC EXAMPLE</Text><FinalizerResponse raw={JSON.stringify(sample)} /></Panel></Shell>;
}

function FinalizerResponse({ raw }: { raw: string }) {
  let result: RecordValue; try { result = object(JSON.parse(raw)); } catch { return <section className="result-panel"><Text className="step">FINALIZER RESPONSE</Text><pre>{raw}</pre></section>; }
  if (!list(result.executive_summary).length && Object.keys(object(result.event_tables)).length) return <InstrumentationHandoff result={result} />;
  const insights = list(result.insights), dashboards = list(result.dashboards), limitations = list(result.limitations), errors = list(result.errors), actions = object(result.actions), quality = object(result.data_quality), lineage = object(result.lineage), context = object(result.context), schema = object(result.schema), metrics = list(result.metrics);
  const actionGroups = Object.entries(actions).filter(([, values]) => Array.isArray(values) && values.length);
  const proofPoints = metrics.length ? metrics : [{ label: 'Insights verified', value: insights.length, detail: 'Evidence-backed findings' }, { label: 'Actions recommended', value: actionGroups.reduce((total, [, values]) => total + list(values).length, 0), detail: 'Decision-ready next steps' }, { label: 'HyperDX views', value: dashboards.length, detail: 'Live charts stay in HyperDX' }];
  return <section className="result-panel"><div className="result-top"><div><Text className="step">FINALIZER RESPONSE</Text><Title type="h2">{text(result.feature) || text(result.feature_name) || 'Decision brief'}</Title><Text className="result-subtitle">A concise, evidence-led handoff for the people making the call.</Text></div><Badge text={text(result.status) || 'partial'} /></div><div className="proof-grid">{proofPoints.slice(0, 4).map((metric, index) => { const item = object(metric); return <article key={index}><Text>{text(item.label) || `Proof point ${index + 1}`}</Text><strong>{text(item.value) || text(item.metric) || '—'}</strong><small>{text(item.detail) || text(item.description) || 'Tracked in this brief'}</small></article>; })}</div><div className="summary-grid">{list(result.executive_summary).map((item, index) => <p key={index}>{typeof item === 'string' ? item : title(item, 'Summary')}</p>)}</div>
    {actionGroups.length > 0 && <Section label="Recommended actions" count={actionGroups.reduce((total, [, values]) => total + list(values).length, 0)}><div className="action-grid">{actionGroups.flatMap(([kind, values]) => list(values).map((item, index) => <article className="action-card" key={`${kind}-${index}`}><Text className="action-kind">{kind.replace('_', ' ')}</Text><strong>{title(item, 'Recommended action')}</strong><p>{detail(item)}</p></article>))}</div></Section>}
    {insights.length > 0 && <Section label="Verified insights" count={insights.length}><div className="insight-list">{insights.map((item, index) => <article key={index}><strong>{title(item, 'Insight')}</strong><p>{detail(item)}</p><Text>{text(object(item).confidence) || 'Evidence-backed'}</Text></article>)}</div></Section>}
    {dashboards.length > 0 && <Section label="HyperDX dashboards" count={dashboards.length}><div className="dashboard-grid">{dashboards.map((item, index) => { const entry = object(item); const url = text(entry.url) || text(entry.hyperdx_url); return <a key={index} href={url || '#'} target="_blank" rel="noreferrer" className="dashboard-card"><Text>HYPERDX</Text><strong>{title(item, 'Dashboard')}</strong>{detail(item) && <small>{detail(item)}</small>}<span>{url ? 'Open live chart ↗' : `Generation ${text(entry.status) || 'pending'}`}</span></a>; })}</div></Section>}
    <div className="governance-grid"><InfoCard label="Data quality" value={text(quality.status) || 'unknown'} items={list(quality.issues)} /><InfoCard label="Context" value={text(context.version) || 'not recorded'} items={list(context.contradictions)} /><InfoCard label="Schema" value={text(schema.execution_status) || 'not recorded'} items={list(schema.tables)} /><InfoCard label="Lineage" value={text(lineage.trace_status) || 'unavailable'} items={list(lineage.stages)} /></div>
    {(list(lineage.stages).length > 0 || text(lineage.langfuse_trace_url)) && <Section label="Agent traceability" count={list(lineage.stages).length}><div className="trace-panel"><div><Text>LANGFUSE TRACE</Text>{text(lineage.langfuse_trace_url) ? <a href={text(lineage.langfuse_trace_url)} target="_blank" rel="noreferrer">Open full trace ↗</a> : <strong>{text(lineage.langfuse_trace_id) || 'Trace link unavailable'}</strong>}</div><div className="trace-stages">{list(lineage.stages).map((stage, index) => { const entry = object(stage); return <article key={index}><strong>{text(entry.agent) || text(entry.name) || `Stage ${index + 1}`}</strong><span>{text(entry.status) || 'recorded'}</span><small>{traceMetrics(entry) || text(entry.duration) || ''}</small></article> })}</div></div></Section>}
    {(limitations.length > 0 || errors.length > 0) && <Section label="Open limitations" count={limitations.length + errors.length}><div className="warning-list">{[...limitations, ...errors].map((item, index) => <p key={index}>{typeof item === 'string' ? item : title(item, 'Review required')}</p>)}</div></Section>}
  </section>;
}
function InstrumentationHandoff({ result }: { result: RecordValue }) {
  const manifest = object(result.ingestion_manifest), eventCounts = object(manifest.event_counts), tables = list(result.tables), aggregates = list(result.aggregations);
  return <section className="result-panel handoff-panel"><div className="result-top"><div><Text className="step">INSTRUMENTATION HANDOFF</Text><Title type="h2">Data foundation ready</Title><Text className="result-subtitle">The event layer is verified and ready for Analytics. A decision brief will appear when the downstream agents publish their evidence.</Text></div><Badge text="analytics next" /></div><div className="proof-grid"><article><Text>Events accepted</Text><strong>{text(manifest.accepted_rows) || '—'}</strong><small>{text(manifest.rejected_rows) || '0'} rejected during ingestion</small></article><article><Text>Unique event IDs</Text><strong>{text(object(manifest.duplicate_evidence).unique_ids) || '—'}</strong><small>Deduplication check complete</small></article><article><Text>Event types</Text><strong>{Object.keys(eventCounts).length || '—'}</strong><small>Ready for funnel analysis</small></article></div><Section label="Verified data assets" count={tables.length + aggregates.length}><div className="action-grid">{tables.map((item, index) => <article className="action-card" key={`table-${index}`}><Text className="action-kind">EVENT TABLE</Text><strong>{text(object(item).name) || 'Table recorded'}</strong><p>{text(object(item).description) || 'Append-only event data.'}</p></article>)}{aggregates.map((item, index) => <article className="action-card" key={`aggregate-${index}`}><Text className="action-kind">ANALYTICS QUERY</Text><strong>{text(object(item).name) || 'Aggregate recorded'}</strong><p>{text(object(item).description) || 'Query ready for Analytics.'}</p></article>)}</div></Section></section>;
}
function Section({ label, count, children }: { label: string; count: number; children: React.ReactNode }) { return <section className="result-section"><div className="section-heading"><Title type="h3">{label}</Title><Text>{count}</Text></div>{children}</section>; }
function InfoCard({ label, value, items }: { label: string; value: string; items: unknown[] }) { return <article className="info-card"><Text>{label}</Text><strong>{value}</strong>{items.length > 0 && <small>{items.length} item{items.length === 1 ? '' : 's'} tracked</small>}</article>; }

function Status({ id }: { id: string }) { const [item, setItem] = useState<Investigation>(); useEffect(() => { let timer: number; const load = async () => { const res = await fetch(`/api/investigations/${id}`); if (res.ok) { const next = await res.json(); setItem(next); if (!['completed', 'failed', 'blocked'].includes(next.status)) timer = window.setTimeout(load, 2000); } }; load(); return () => clearTimeout(timer); }, [id]); return <Shell><Panel className="content-card" padding="xl" hasBorder hasShadow><Text className="step">REVIEW {id.slice(0, 8)}</Text><div className="status-heading"><Title type="h2">{item?.progress || 'Preparing your decision brief…'}</Title><Badge text={item?.status || 'loading'} /></div><section className="stages">{['instrumentation-agent', 'analytics-agent', 'context-agent', 'finalizer-agent'].map(name => { const stage = item?.agents?.find(agent => agent.agent === name); return <article key={name}><div><strong>{name.replace('-agent', '')}</strong><Text>{stage?.progress || 'Waiting'}</Text></div><Badge text={stage?.status || 'queued'} />{stage?.error_message && <p className="error">{stage.error_message}</p>}</article>; })}</section>{item?.final_result && <FinalizerResponse raw={item.final_result} />}{item?.error_message && <p className="error">{item.error_message}</p>}</Panel></Shell>; }
createRoot(document.getElementById('root')!).render(<App />);
